### ISSUE TITLE
BUG: TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by xoxoj** [ctf0/Laravel-Media-Manager#100]
> What version of Laravel are you using? (nothing lower than v5.4).

5.8

> is it an issue related to installation or usage ?

usage

> what is the error you are getting ?

`[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'value' of undefined"`

> Extra Info "attaching a screen shot would be very helpful"

![999](https://user-images.githubusercontent.com/1118723/57924252-3b515b00-78d7-11e9-9652-eb48df7ba92d.jpg)

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
how to repo, what happened prior to this error ?

**Comment by ctf0** [comment]
this is related to move list propagation, will be fixed in next release
