### ISSUE TITLE
BUG: Uncaught TypeError: Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by xoxoj** [ctf0/Laravel-Media-Manager#101]
> What version of Laravel are you using? (nothing lower than v5.4).

5.8

> is it an issue related to installation or usage ?

usage

> what is the error you are getting ?

`Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at app.js:3013`

> Extra Info "attaching a screen shot would be very helpful"

![999](https://user-images.githubusercontent.com/1118723/57924645-3e991680-78d8-11e9-99c4-37f943c11bce.jpg)

![999a](https://user-images.githubusercontent.com/1118723/57924650-448ef780-78d8-11e9-941c-daea4263e773.jpg)

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
when did that error occur ? on the manager load or when u tried to open the image editor diff ?

**Comment by xoxoj** [comment]
@ctf0 Specifically, I forgot, how did this error appear, as if I clicked on the button, edit it?

**Comment by ctf0** [comment]
the issue might happen in 2 cases `toggle the img preview scroll btn, center the img diff editor`

i cant reproduce, if u still have the issue, plz report back
