### ISSUE TITLE
Why the page is loading blank?

### ISSUE THREAD

**Issue by yusufulusoy** [ctf0/Laravel-Media-Manager#103]
> What version of Laravel are you using? (nothing lower than v5.4).

Laravel v5.8

> what is the error you are getting ?

I installed media manager verbatim of readme file but when I open **localhost:8000/media** url the page is coming empty.

> Extra Info "attaching a screen shot would be very helpful"

I don't get any error from console:
https://i.ibb.co/hXsvxgY/Screenshot-1.png

> Do You Know A Solution For this Issue ?

Source code loading. First of loading I see black page and components variables like {{ variable }} but after component mount page remain white.

My app.js file

```
window.Vue = require('vue');
require('../assets/vendor/MediaManager/js/manager');

//Vue.use(CKEditor);

//Vue.component('example-component', require('./components/ExampleComponent.vue').default);

const app = new Vue({
    el: '#app',
});
```

**Comment by ctf0** [comment]
plz check the console and reply back with what u get

**Comment by yusufulusoy** [comment]
> plz check the console and reply back with what u get

@ctf0 No error at console. I attached screenshot of empty page and console.

**Comment by ctf0** [comment]
but without any errors how can i debug the issue ?

**Comment by yusufulusoy** [comment]
> but without any errors how can i debug the issue ?

Yes, I've asked if someone has had the same problem before. But I can't found any solution. No error, no UI. I removed package from composer. Thank you.
