### ISSUE TITLE
Integration to Vue SPA

### ISSUE THREAD

**Issue by sergiuwd** [ctf0/Laravel-Media-Manager#105]
Is there a simple way of integrating this into a SPA? I am using Laravel only as a backend and a Vue SPA as the frontend, but I see that this package relies on Laravel with config, translation, etc. Has anyone successfully integrated this into a SPA?

**Comment by Alvazz** [comment]
if you want do this, need change the source code by youself. bcs, this project dependent alot of Laravel file system feature

**Comment by ctf0** [comment]
the package use ajax for all of its ops, so using it with spa wont be an issue unless am missing something ?

**Comment by sergiuwd** [comment]
It is, 'cause it's heavily relaying on Laravel's `config` and `translation` files.

**Comment by ctf0** [comment]
not necessarily, as long as u can deliver an alternative value to the needed configs and trans then u r good to go.

all the data are being sent to the components through props to make it easier to add/remove any thing u want

**Comment by BechirAhmed** [comment]
Any one have a solution for this integration, or a clear way to integrate the package?
