### ISSUE TITLE
Laravel-Media-Manager Installation via Node.js

### ISSUE THREAD

**Issue by DevPaulVarghese** [ctf0/Laravel-Media-Manager#106]
Hi, 

Thank you for providing such a wonderful file management solution. 

Can you please let me know how I can install the "Laravel-Media-Manager" as a Node.js package and then load it as a vue component in within a .vue file?

Looking forward to your reply.

Thank You & Kind Regards,
Paul

**Comment by ctf0** [comment]
the package depend on laravel which is a PHP , however if u mean installing the dep with `npm` then check https://github.com/ctf0/Laravel-Media-Manager#installation
