### ISSUE TITLE
Can not save image after edit

### ISSUE THREAD

**Issue by shuuichiakai** [ctf0/Laravel-Media-Manager#107]
hi. i can not save image after edit. 
![Screen Shot 2019-06-17 at 7 43 42 AM](https://user-images.githubusercontent.com/7381068/59571100-e706ea00-90d3-11e9-9d64-51c750aa88f3.png)

**Comment by ctf0** [comment]
there is a template for opening a ticket, plz use it

**Comment by ctf0** [comment]
i cant reproduce
