### ISSUE TITLE
[Feature] German translation

### ISSUE THREAD

**Issue by Christo-Stoyanov** [ctf0/Laravel-Media-Manager#111]
Hey, thx for that really nice package! Here is a german lang translation. 

https://www.12file.com/d/314003004b8daa94349580eb74d47103622c12233389abab55e7b9956d6cfaa86a91a6a66bf9acdc10e886f5c65279f8a29e8081c9e2fac971edefe8debeab36bb837ab401497d16c1c0ccd4e4132f73d0b336e78c8301918bf6712bb986f9aa6c92ad4f

File will be available for 30 days.

Kind regards
CS

**Comment by ctf0** [comment]
many thanx for this, can u plz submit a PR instead ?
