### ISSUE TITLE
Support laravel 6

### ISSUE THREAD

**Issue by decreative1989** [ctf0/Laravel-Media-Manager#115]
I Need this package can support for Laravel 6.

**Comment by ctf0** [comment]
i'vent tested on v6 yet, however u can try this trick and reply back https://twitter.com/jessarchercodes/status/1169038266311397376?s=20

**Comment by jasperf** [comment]
```
Symfony\Component\Debug\Exception\FatalThrowableError : Call to undefined function ctf0\MediaManager\array_get()
at /home/me/Project/something-v3/vendor/ctf0/media-manager/src/MediaManagerServiceProvider.php:96
```

Is one other issue because of replacement of `array_get` by `Arr::get()` That is besides the composer.json Laravel Framework requirement change. Have not worked out a full fix yet. But thought it was good to mention that here.

**Comment by chutuan** [comment]
@ctf0 array_get is removed on v6.0 and replaced by Arr::get()

**Comment by ctf0** [comment]
the array & str was changed in the master but wasnt released yet, i will publish a couple of releases to address this issue soon.

**Comment by jasperf** [comment]
Great to hear that @ctf0 ! Working on the app upgrade and dealing with a few package issues. Hope I can get Laravel Media Manager to play nice again soon.

**Comment by ctf0** [comment]
sorry for the late reply, plz check the latest updates and reply back if anything is out of place b4 i push the new release.

[here are the changes made so far](https://github.com/ctf0/Laravel-Media-Manager/blob/master/logs/v3.4.0.txt)

**Comment by jasperf** [comment]
Well I think removing deprecated Laravel helpers, including allowing new Laravel version in package is about it so go ahead. We will update and test in Laravel 6.0 . If need be you could let us know the branch and then we test it.

**Comment by ctf0** [comment]
ok, i will push it later today
