### ISSUE TITLE
how to save uploaded files to db ?

### ISSUE THREAD

**Issue by jaccborn** [ctf0/Laravel-Media-Manager#116]
i've read the the document, but i can't find how can i use the mysql  exists datas.
i'm not familiar with vue, i just want use this project as a media module.
please tell me how can i do it, thank u!

**Comment by ctf0** [comment]
1- there is a template for the tickets, plz use it.
2- am not sure what `exists datas` u mean

**Comment by jaccborn** [comment]
thank u for u reply.
i am not see the tickets template,can u apply a pic for me?
the exists datas mean that i want use my api , and it will be return the data from mysql database.
look like below data struct:
![image](https://user-images.githubusercontent.com/12455286/65808738-c23d0b00-e1c8-11e9-9025-f298ab98e186.png)

**Comment by ctf0** [comment]
> i am not see the tickets template,can u apply a pic for me?

![Screen Shot 2019-09-28 at 3 13 21 AM](https://user-images.githubusercontent.com/7388088/65809513-272f3b80-e19e-11e9-988f-deb469e519b7.png)

> look like below data struct:

u can achieve that in more than one way
- use events https://github.com/ctf0/Laravel-Media-Manager#events
- use a custom controller https://github.com/ctf0/Laravel-Media-Manager/wiki/Have-More-Control-On-Uploads
- if u r using the manager inside a form, follow https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal

**Comment by jaccborn** [comment]
thank u very much!
hope u happy every day. good luck for u.




发自我的iPhone

------------------ Original ------------------
