### ISSUE TITLE
[BUG]Cannot read property 'settings' of undefined

### ISSUE THREAD

**Issue by efectn** [ctf0/Laravel-Media-Manager#118]
I have this error ;

app.js:73768 Uncaught TypeError: Cannot read property 'settings' of undefined
    at HTMLDocument.clickHandler

Screnshoots :

http://prntscr.com/phj04u
http://prntscr.com/phj0hw

**Comment by ctf0** [comment]
there is a template, plz use it

**Comment by ctf0** [comment]
i believe ur error is related for not publishing the assets, but without more info of ur setup i cant really help

**Comment by efectn** [comment]
I make setup stages . And i published assets .

**Comment by ctf0** [comment]
make a repo with ur setup and send me the link to test with
