### ISSUE TITLE
Modal won't open

### ISSUE THREAD

**Issue by mvdhoop** [ctf0/Laravel-Media-Manager#124]
Hi, i'm trying to use the MediaManager within a form with the modal functionality. But I just can't get it to work, it just won't open a modal.
I'm not getting any errors, I can see the modal got created in the source:

`<div class="modal mm-animated fadeIn is-active modal-manager__Inmodal">{more code}</div>`

But it stays hidden. Also the html markup is not there, when I disable 'display: none' in the inspector it isn't showing a nice styled modal.

When I try the 'select gallery folder' button it does fill the input field with the first folder it can find in the MediaManager. But no modal showed to get there...

Anyone know what could be wrong? I followed the wiki explanation, any steps missing there or what am I doing wrong?

**Comment by ctf0** [comment]
why no one use the ticket template ? 😠 

anyway, plz create a repo so i can reproduce
