### ISSUE TITLE
[BUG] Undefined variable: patterns

### ISSUE THREAD

**Issue by TeeJay-Codes** [ctf0/Laravel-Media-Manager#125]
> What version of Laravel are you using? (nothing lower than v5.4).

Laravel 5.8

> is it an issue related to installation or usage ?

All installation procedure ran successfully

> what is the error you are getting ?

Undefined variable: patterns (View: ../resources/views/vendor/MediaManager/_manager.blade.php)

> Extra Info "attaching a screen shot would be very helpful"

New installation on an existing Laravel 5.8 app. 
I see that you have previously addressed this issue, but still getting the same error even though the code is updated.

<img width="774" alt="Screenshot 2019-11-21 at 02 56 47" src="https://user-images.githubusercontent.com/3678670/69293920-9a878380-0c0a-11ea-86e8-b9cac00995bc.png">

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
the variable comes from here 
https://github.com/ctf0/Laravel-Media-Manager/blob/824049e25ee89bd8b8e3f1a009923599a1233ac7/src/MediaManagerServiceProvider.php#L75-L106

am not sure why this happens with you but try to clear caching and use `composer dump`

**Comment by TeeJay-Codes** [comment]
Oh,
My apologies, I didn't run "npm run dev" to copy the assets.
Then I had to migrate the database also.
