### ISSUE TITLE
File Uploading on root storage root directory 

### ISSUE THREAD

**Issue by dpkpaa** [ctf0/Laravel-Media-Manager#126]
> What version of Laravel are you using? (nothing lower than v5.4).
Laravel 6.3
...

> is it an issue related to installation or usage ?
Usage
...

> what is the error you are getting ?
When i am trying to upload a file in new folder is going to root folder
and when in refreshed that directory and uploading a file is going into the right directory 
...

> Extra Info "attaching a screen shot would be very helpful"

...

> Do You Know A Solution For this Issue ?
yes i need a solution because i stacked in development please help me 
...

**Comment by ctf0** [comment]
sorry for that, will be fixed in next release
