### ISSUE TITLE
[BUG] PCRE2 backward incompatible for regex patterns

### ISSUE THREAD

**Issue by vasishth80987** [ctf0/Laravel-Media-Manager#127]
> What version of Laravel are you using? (nothing lower than v5.4).

6.x

> is it an issue related to installation or usage ?

Yes

> what is the error you are getting ?

exception: "ErrorException"
file: "/vendor/ctf0/media-manager/src/App/Controllers/Modules/Utils.php"
line: 50
message: "preg_replace(): Compilation failed: invalid range in character class at offset 27"

> Do You Know A Solution For this Issue ?

This is an issue specific to PHP 7.3 and newer. PHP PCRE engine has migrated to PCRE2.
So the regex pattern used for compilation needs to be compatible with the new regex syntax. In my case the pattern generated was

 _(script.*?\/script)|[^(_-\s)a-zA-Z0-9]+_

The _-\s has to be _\-\s as per the new syntax(please cross check this `https://wiki.php.net/rfc/pcre2-migration#backward_incompatible_changes`)

**Comment by ctf0** [comment]
> The _-\s has to be _-\s as

???

**Comment by vasishth80987** [comment]
Aplogies for the typo,

It should be _\\-\s, the hyphen has to escaped.

**Comment by vasishth80987** [comment]
Resolved it, by changing it in the config variable 'allowed_folderNames_chars' and 'allowed_fileNames_chars'.

**Comment by antlusher** [comment]
Hello all, still having regex issues for file creation, for now, I've changed to empty strings in LMM config.. Not sure how to fix this, will have a look when I get the opportunity 

Cheers
