### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oThTJx** [ctf0/Laravel-Media-Manager#129]
php7.4
![image](https://user-images.githubusercontent.com/46552592/72531607-c5a9ee80-38ac-11ea-801e-0280a6ad6947.png)

**Comment by ctf0** [comment]
the bug report have a template, plz use it.

the error is related to not finding the config key
https://github.com/ctf0/Laravel-Media-Manager/blob/ac7af4440329d41ec13053fea61fbef6e453562a/src/config/mediaManager.php#L12

without further info i cant help u

**Comment by oThTJx** [comment]
This message appears during installation. Should I create the configuration file first?
![image](https://user-images.githubusercontent.com/46552592/72587663-db60f780-3930-11ea-8d19-9abd9fb5c67b.png)
这里获取的配置信息是null,安装的时候应该获取的是你的配置信息

**Comment by oThTJx** [comment]
The configuration information obtained here is null. The configuration information should be obtained at the time of installation

**Comment by ctf0** [comment]
can u make a repo for me to test with ?
