### ISSUE TITLE
The Mix manifest does not exist Issue

### ISSUE THREAD

**Issue by yousuf-hossain-shanto** [ctf0/Laravel-Media-Manager#13]
Hello, Please Help me!

When I navigate http://localhost:8000/media first time. This show Error. Error Message is 

The Mix manifest does not exist. (View: H:\softking\laravel\TSKads\resources\views\vendor\MediaManager\media-bulma.blade.php)

**Comment by ctf0** [comment]
https://laravel.com/docs/5.5/mix otherwise rename `mix` to `asset`
