### ISSUE TITLE
could someone explain this error syntax error, unexpected ',' (View: E:\laravel\kedaok\kedaokayne\resources\views\vendor\MediaManager\_manager.blade.php

### ISSUE THREAD

**Issue by mostafahesham-dev** [ctf0/Laravel-Media-Manager#133]
syntax error, unexpected ',' (View: E:\laravel\kedaok\kedaokayne\resources\views\vendor\MediaManager\_manager.blade.php
this error happend when accessing media route or include _manager.blade.php

**Comment by ctf0** [comment]
the ticket have a template, plz use it
