### ISSUE TITLE
[Bug] syntax error, unexpected ',' (View: ..\resources\views\vendor\MediaManager\_manager.blade.php)

### ISSUE THREAD

**Issue by mostafahesham-dev** [ctf0/Laravel-Media-Manager#134]
> What version of Laravel are you using? (nothing lower than v5.4).

5.8

> is it an issue related to installation or usage ?

no

> what is the error you are getting ?

`syntax error, unexpected ',' (View:
{project_path}\resources\views\vendor\MediaManager\_manager.blade.php)`

> Extra Info "attaching a screen shot would be very helpful"

![image](https://user-images.githubusercontent.com/60550928/73597275-d1471780-4532-11ea-9002-3a5edd83b7b2.png)

> Do You Know A Solution For this Issue ?

no

**Comment by ctf0** [comment]
it clearly says u have an extra `,` on line 581, which is 

https://github.com/ctf0/Laravel-Media-Manager/blob/a43a59c2d816e559961c5bda3d93c03fe0ba1510/src/resources/views/_manager.blade.php#L581

can u show my the full screen shoot ?
