### ISSUE TITLE
[Question] Has this tool options for SEO?

### ISSUE THREAD

**Issue by LuismiLabs** [ctf0/Laravel-Media-Manager#135]
Need meta capabilities, ie image title, image alt text, image meta description.
Need to list mapped categories for each images.
Does this tool work for that?

**Comment by ctf0** [comment]
chk the wiki https://github.com/ctf0/Laravel-Media-Manager/wiki/Preview-Files-Before-Uploading

and
https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal
