### ISSUE TITLE
[BUG] dropzone dependency was not found

### ISSUE THREAD

**Issue by boutzamat** [ctf0/Laravel-Media-Manager#137]
> What version of Laravel are you using? (nothing lower than v5.4).

6.12

> is it an issue related to installation or usage ?

Installation

> what is the error you are getting ?

The dependency was not found: 

* dropzone in ./resources/assets/vendor/MediaManager/js/modules/upload.js

> Extra Info "attaching a screen shot would be very helpful"

...
![image](https://user-images.githubusercontent.com/4305046/74479580-b0c27a00-4eaf-11ea-9c5e-89ab71e75d94.png)

> Do You Know A Solution For this Issue ?

The CLI says i can install it by running: npm install --save dropzone, which i already did but the error remains.
I checked the node_modules folder and dropzone does exist in there.

I followed every step in the documentation, but instead of yarn i use npm. I did use this command to download the packages: `npm install vue vue-ls vue-infinite-loading vue-image-compare2 vue-tippy@v1 vue2-filters vue-input-autowidth vue-notif vue-clipboard2 vue-awesome@v2 vue-touch@next vue-focuspoint-component axios dropzone cropperjs keycode lottie-web plyr fuse.js music-metadata-browser --save`

**Comment by boutzamat** [comment]
I know i shouldn't post an issue within an issue, but imma go for it.

I made a new install and this time i used yarn (even though i never use it, and it is bad practice to use 2 different dependency managers in the same project), and this time it is installed.

Now i have another issue with this package. After installing, running "npm run dev", the console throws the following errors at me:

app.js:38081 [Vue warn]: Unknown custom element: <my-notification> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

[Vue warn]: Unknown custom element: <media-manager> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

**Comment by boutzamat** [comment]
I just tried installing it on a fresh installation using yarn, as i suspected that it might be NPM that was causing the issue, but the problem remains the same.

**Comment by ctf0** [comment]
can u make a repo for me to repro ?

**Comment by boutzamat** [comment]
Yes ofcourse. Should i just create a Git Repo with the project for you to install?

It happens with a fresh install, so you should encounter the issue if you try to install it on a fresh Laravel installation following your installation guide.

If you still want to, i can push my fresh installation to a new Git Repo.

**Comment by ctf0** [comment]
> If you still want to, i can push my fresh installation to a new Git Repo.

that would be great

**Comment by boutzamat** [comment]
Gotcha. Here's a link for the repo: https://github.com/boutzamat/Media-Manager-Sandbox

**Comment by ctf0** [comment]
link is 404

**Comment by boutzamat** [comment]
Sorry it was set to a private repository. It should be public now

**Comment by ctf0** [comment]
i managed to fix it with updating the deps in `package.json`

![demo](https://user-images.githubusercontent.com/7388088/74587362-191d7280-4ffa-11ea-9038-b49ce1de3b56.png)

**Comment by boutzamat** [comment]
Thanks alot for taking time to look at it and providing the fix.

Are you going to patch it or should I just manually apply the fix?

Thanks again !

**Comment by ctf0** [comment]
actually the issue was related to dropzone installed version, as u can see in 
```
yarn add vue vue-ls vue-infinite-loading vue-image-compare2 vue-tippy@v1 vue2-filters vue-input-autowidth vue-notif vue-clipboard2 vue-awesome@v2 vue-touch@next vue-focuspoint-component axios dropzone cropperjs keycode lottie-web plyr fuse.js music-metadata-browser idb-keyval
```

we dont require specific version for dropzone, so this was more of try & error solution 😄
