### ISSUE TITLE
[BUG] Trying to access array offset on value of type null in `MediaManagerServiceProvider.php`

### ISSUE THREAD

**Issue by antlusher** [ctf0/Laravel-Media-Manager#138]
> What version of Laravel are you using? (nothing lower than v5.4).
6.x
...

> is it an issue related to installation or usage ?
Install
...

> what is the error you are getting ?
Trying to access array offset on value of type null 
vendor/ctf0/media-manager/src/MediaManagerServiceProvider.php:82

**->disk($config['storage_disk'])**

...

> Extra Info "attaching a screen shot would be very helpful"
![Screenshot 2020-02-26 at 09 57 39](https://user-images.githubusercontent.com/2495026/75333737-92c92200-587e-11ea-947f-816aac950a49.png)

...

> Do You Know A Solution For this Issue ?
Maybe the PHP version is incorrect? I'm currently using 7.4

Can we add 7.4 support? Due to a lot of packages relies on. 

Or, unless I've overlooked, could we add environment requirements and the top of documents?

Cheers!
...

**Comment by ctf0** [comment]
this is due for not publishing the config, also 

https://github.com/ctf0/Laravel-Media-Manager/blob/73d9639cc1dd4eee2f59626109c0efb3ba6d4c38/composer.json#L21

which means we support any version that starts with `7`

**Comment by nrbrttth** [comment]
@ctf0 I have the same issue with a fresh Laravel 6.x installation. I ran the composer require and got the same error message. Weren't able to get to the publish part.

**Comment by ctf0** [comment]
@nrbrttth can u make a repo to test with ?

**Comment by nrbrttth** [comment]
> @nrbrttth can u make a repo to test with ?

@ctf0 https://github.com/nrbrttth/media-manager
Just a plain 6.x Laravel. Tried to run `composer require ctf0/media-manager` and got the error message mentioned above.

Thank you for your time!

**Comment by nrbrttth** [comment]
My temporary solution was to copy the config/mediaManager.php file to Laravel's config folder before installing the Media Manager with composer.

**Comment by ctf0** [comment]
@nrbrttth @antlusher u r correct, i've never encountered this in the demo repo, but its fixed now, plz check the latest release, thanx for ur report

**Comment by nrbrttth** [comment]
@ctf0 Thank you, it's working now!
