### ISSUE TITLE
[feature] append to url query string instead of replace

### ISSUE THREAD

**Issue by gmlo89** [ctf0/Laravel-Media-Manager#142]
Hi

How can I prevent updating my browser url while browsing directories?

while i am browsing the directories the query string is updated.

![ezgif-7-110bb362fcd5](https://user-images.githubusercontent.com/874420/76282192-499ca900-6254-11ea-804a-cc999c650d0c.gif)

**Comment by ctf0** [comment]
why u want to disable it ?

**Comment by gmlo89** [comment]
because I use it in modal mode, if the user wants to update the site he will have an error

**Comment by ctf0** [comment]
the url update doesnt work while in modal mode

**Comment by gmlo89** [comment]
![ezgif-7-c9a11da54895](https://user-images.githubusercontent.com/874420/76339602-8cdc3380-62b7-11ea-8a21-8047b6014682.gif)

**Comment by ctf0** [comment]
the manager add one qs of 'path' which when opening 'home' it doesnt gets added as expected, so ...

**Comment by ctf0** [comment]
oh ok, i got it, can be fixed

**Comment by ctf0** [comment]
plz check latest commit and reply back

**Comment by gmlo89** [comment]
Excellent!

Thanks a lot :)
