### ISSUE TITLE
[BUG] Undefined index: timestamp with s3

### ISSUE THREAD

**Issue by vanthao03596** [ctf0/Laravel-Media-Manager#143]
> What version of Laravel are you using? (nothing lower than v5.4).

I'm using laravel 7

> is it an issue related to installation or usage ?

Usage issue

> what is the error you are getting ?

After clone demo repo, I set up file system with league/flysystem-aws-s3-v3. When i hit route /media i get error "Undefined index: timestamp"

> Extra Info "attaching a screen shot would be very helpful"

![1](https://user-images.githubusercontent.com/34786441/77649274-297f2080-6f9c-11ea-9bd3-d6dd179a94c5.png)

> Do You Know A Solution For this Issue ?

I tried dd($storageFolders) and get result with no index timestamp in array but dont know how to fix.
![2](https://user-images.githubusercontent.com/34786441/77649396-60553680-6f9c-11ea-9313-0cd1e9a26dce.png)

**Comment by ctf0** [comment]
am not sure if something has changed in the new version of the drivers, but plz recheck with the latest commit and reply back

**Comment by vanthao03596** [comment]
@ctf0  It work now but take long time to response.
I tried same storage config with laravel/elfinder it still fast.
![1](https://user-images.githubusercontent.com/34786441/77712294-f83b3a80-7005-11ea-9d4e-93d44be40246.png)

**Comment by ctf0** [comment]
how much it takes without the manager ?

**Comment by vanthao03596** [comment]
It take about 30 second

**Comment by ctf0** [comment]
this is probably related to s3 auth handshake & also ur connection speed

**Comment by vanthao03596** [comment]
> how much it takes without the manager ?

Ah i dont understand your question. When i use elfinder it take 2-3s.

**Comment by ctf0** [comment]
does elfinder show image thumbs when it retrieves them or just names ?

**Comment by vanthao03596** [comment]
It show only name, when click preview it will load preview leftsite
![1](https://user-images.githubusercontent.com/34786441/77718626-ff6a4480-7015-11ea-8c77-ca9ffe0b8186.png)

**Comment by ctf0** [comment]
can u make a repo for me to test with ?

**Comment by vanthao03596** [comment]
Yes.

**Comment by vanthao03596** [comment]
for private s3 info i created private repo @ctf0 
https://github.com/vanthao03596/issue-media/invitations

**Comment by ctf0** [comment]
awesome, i will see what i can do, thnx

**Comment by ctf0** [comment]
@vanthao03596 i've made a new ticket for the loading issue, lets continue over there.

**Comment by ctf0** [comment]
@vanthao03596 plz disable the fs cache and retest with elfinder & reply back with the request time.

**Comment by vanthao03596** [comment]
Enfinder take a second to load.
![ezgif com-optimize](https://user-images.githubusercontent.com/34786441/77815454-c8676200-70ed-11ea-976a-9c5bbe113a07.gif)
After run composer update Laravel-Media-Manager take 9 second.
![1](https://user-images.githubusercontent.com/34786441/77815464-e03ee600-70ed-11ea-9026-38611d43c9be.png)

**Comment by ctf0** [comment]
ok
