### ISSUE TITLE
[Question] Show Folder by Default

### ISSUE THREAD

**Issue by jasperf** [ctf0/Laravel-Media-Manager#146]
Currently when we add a folder it is not shown. Not until we click the display folders option. When we do only folders are shown. Is there also an option to show images and folders? Also can we turn this on by default?

```php
<div class="control">
  <button @click="showFilesOfType('folder')"
      v-tippy
      title="{{ trans('MediaManager::messages.filter_by', ['attr' => trans('MediaManager::messages.folder')]) }}"
      class="button"
      :class="{'is-link': filterNameIs('folder')}"
      :disabled="!btnFilter('folder') || isLoading">
      <span class="icon"><icon name="folder"></icon></span>
  </button>
</div>
```

**Comment by ctf0** [comment]
am not sure what is the issue :confused:

**Comment by jasperf** [comment]
Well I see I cannot have and images and folders clicked / turned on by default. Seems I can only load folders or images. .. But perhaps that is only my setup. I will have a look at things.
