### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by ritwikBiswas007** [ctf0/Laravel-Media-Manager#149]
> What version of Laravel are you using? (nothing lower than v6).

Version 7

> is it an issue related to installation or usage ?

Usage

> what is the error you are getting ?

Trying to access array offset on value of type null

> Extra Info "attaching a screen shot would be very helpful"

![Opera Snapshot_2020-05-12_182518_localhost](https://user-images.githubusercontent.com/62345223/81693933-4ef9b800-947e-11ea-820f-934757189de2.png)

> Do You Know A Solution For this Issue ?

No

**Comment by ctf0** [comment]
have u published the packages assets ?

**Comment by ritwikBiswas007** [comment]
Yes I have Published the package assets... Can You tell me how Can I use the media manager in a modal of my form to choose images.. Actually I am new to vue js.

**Comment by ctf0** [comment]
> Yes I have Published the package assets

plz make a repo so i can repro with

>Can You tell me how Can I use the media manager in a modal of my form 

check 
- https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal
- https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-With-Any-WYSIWYG-Editor

**Comment by ritwikBiswas007** [comment]
Ok the problem is solved. Thank you so much for guiding me..
