### ISSUE TITLE
[Question] How to use with laravel API

### ISSUE THREAD

**Issue by ritwikBiswas007** [ctf0/Laravel-Media-Manager#151]
I am using Nuxt js as my frontend Framework and Laravel as my backend API.  

Please Tell me How can I use this file manager in this situtation

Please reply

**Comment by ctf0** [comment]
there are a couple of tickets for the same usage, plz check them

**Comment by ritwikBiswas007** [comment]
Please Provide some reference tickets as I am Unable to find a relavant one

**Comment by ctf0** [comment]
https://github.com/ctf0/Laravel-Media-Manager/issues?q=is%3Aissue+spa+is%3Aclosed+
