### ISSUE TITLE
[BUG] Can't install

### ISSUE THREAD

**Issue by elfeffe** [ctf0/Laravel-Media-Manager#155]
I get this in composer

Problem 1
    - Conclusion: don't install ctf0/media-manager v3.7.1
    - Conclusion: remove maennchen/zipstream-php 2.1.0
    - Installation request for ctf0/media-manager ^3.7 -> satisfiable by ctf0/media-manager[v3.7.0, v3.7.1].
    - Conclusion: don't install maennchen/zipstream-php 2.1.0
    - ctf0/media-manager v3.7.0 requires maennchen/zipstream-php ~1.0 -> satisfiable by maennchen/zipstream-php[1.0.0, 1.1.0, 1.2.0, v1.0.0-alpha.1, v1.0.0-alpha.2].
    - Can only install one of: maennchen/zipstream-php[1.0.0, 2.1.0].
    - Can only install one of: maennchen/zipstream-php[1.1.0, 2.1.0].
    - Can only install one of: maennchen/zipstream-php[1.2.0, 2.1.0].
    - Can only install one of: maennchen/zipstream-php[v1.0.0-alpha.1, 2.1.0].
    - Can only install one of: maennchen/zipstream-php[v1.0.0-alpha.2, 2.1.0].
    - Installation request for maennchen/zipstream-php (locked at 2.1.0) -> satisfiable by maennchen/zipstream-php[2.1.0].

**Comment by ctf0** [comment]
its seems u already have `maennchen/zipstream-php` which is a higher version than what the package reqs.

**Comment by ctf0** [comment]
will be fixed in next release, thanx for reporting.
