### ISSUE TITLE
[Feature] Posibility to add assets directly instead of using Mix

### ISSUE THREAD

**Issue by elfeffe** [ctf0/Laravel-Media-Manager#156]
Some of us, have an admin layout, full of JS and CSS, and a front layout with minimum requirements to improve page speed.
If you add all the needed assets (Vue for example) to the Mix, they will be added to the front and admin.
Probably this can be resolved using 2 mixes, but I don't know how to do that.

**Comment by ctf0** [comment]
am not really sure what u r after, but [manager.js](https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/assets/js/manager.js) doesnt have to be compiled as it is.

as stated in the [wiki](https://github.com/ctf0/Laravel-Media-Manager/wiki)
> remove any packages registration that you may already have in your app from `manager.js` to avoid duplications and keep your files as small as possible

**Comment by ctf0** [comment]
as for to keep files as small as possible, i would recommend using code splitting & `mix.extract()`

**Comment by ctf0** [comment]
> Probably this can be resolved using 2 mixes, but I don't know how to do that.

https://www.compulsivecoders.com/tech/how-to-build-multiple-vendors-using-laravel-mix/
