### ISSUE TITLE
Pick file from media manager(pop up window)

### ISSUE THREAD

**Issue by wei-jinn** [ctf0/Laravel-Media-Manager#157]
Greetings ctf0. 

I am developing a feature that allows user to pick profile photo from Laravel-Media-Manager, with the flow below:
1. Click button "select photo from Media Manager"
2. Media Manager interface pops up, now user can select any photo from here.
3. Select a photo, and click confirm(newly added button on Media Manager). Then the file path is inserted into the user database under column "profile_photo_path"
4. User will be direct to the same page where he/she clicks to pick a profile photo.
5. Done.

Do you have any suggestion on making this happen? Thank you.

By the way, your media manager is fantastic in term of both visual design and function! Salute!

**Comment by ctf0** [comment]
thanx for the kind words, i believe what u want is already in the wiki 

- https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-With-Any-WYSIWYG-Editor
- https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal

**Comment by wei-jinn** [comment]
Thanks ctf0 for highlighting it for me! Btw, despite having the media manager works normally, I found out that I could not move the file into folder as the button is disabled. Could you suggest any possible issue happened(as image shown) and what could I do about it?

![image](https://user-images.githubusercontent.com/45649909/87761871-c3692280-c844-11ea-8ca5-affd0f8af237.png)
