### ISSUE TITLE
[BUG] Target class [ctf0\MediaManager\Controllers\MediaController] does not exist & Route [media.files] not defined.

### ISSUE THREAD

**Issue by simplyaakif** [ctf0/Laravel-Media-Manager#158]
> What version of Laravel are you using? (nothing lower than v6).

"laravel/framework": "6.0.1",

> is it an issue related to installation or usage ?

Installation

> what is the error you are getting ?

Backstory 
Everything was working great on my local & production server till i got hit with ransomware and lost all my local environment, when i tried to recreate a new local environment from my github repository now i am getting these strange errors 
I get this error on my previously working code
Route [media.files] not defined. On the page where i used the media manger in a modal 
Alternately i get this error if i view localhost/media route (Demo for the Media Upload)
Target class [ctf0\MediaManager\Controllers\MediaController] does not exist

> Extra Info "attaching a screen shot would be very helpful"

![image](https://user-images.githubusercontent.com/26874542/91823843-49a1c280-ec53-11ea-8183-1e7ccb9d7e62.png)
![image](https://user-images.githubusercontent.com/26874542/91823873-57574800-ec53-11ea-8ae8-68ec788adbde.png)

> Things i have tried so far

Reinstalling the Media manager package.
Dumping composer auto load
Manually placing Media manager service provider in config app service provider list
Rerunning all the mentioned steps in the installation section

**Comment by ctf0** [comment]
- 1st img
have u ran the `php artisan lmm:setup` command ?

- 2nd img
you can test with the demo repo [here](https://github.com/ctf0/demos/tree/media-manager)
