### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by vhchung** [ctf0/Laravel-Media-Manager#16]
When I open `localhost:8000/media`. I got this error
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

The error occurred at this line
```
module.exports = new Vuemit()
```

How can I fix this error?

**Comment by ctf0** [comment]
can u show me the full console error ? maybe a screenshot ?

**Comment by vhchung** [comment]
My screenshot:

![mediamanager_error](https://user-images.githubusercontent.com/7991775/32013657-f603118a-b9e5-11e7-8587-20f57c0fa991.png)

Hope this can help you figure out the error.

**Comment by ctf0** [comment]
this is the first time to see this issue but try [this](https://ctf0.wordpress.com/2017/09/12/laravel-mix-es6/) if still getting issue , then also try installing `babel-plugin-transform-runtime`

vuemit comes already pre-installed with the presets, so just follow the configuration from the article

also try with [google](https://www.google.com.eg/search?q=Cannot+assign+to+read+only+property+%27exports%27+of+object+%27%23%3CObject%3E%27&oq=Cannot+assign+to+read+only+property+%27exports%27+of+object+%27%23%3CObject%3E%27&aqs=chrome..69i57j69i61j0j69i61l2.3116j0j4&sourceid=chrome&ie=UTF-8) as its a general webpack problem

**Comment by vhchung** [comment]
[Your link](https://ctf0.wordpress.com/2017/09/12/laravel-mix-es6/) help me to fix this issue. Thank you very much
