### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by AhmedBenCheikh** [ctf0/Laravel-Media-Manager#161]
i use laravel 6.18.41

> is it an issue related to installation or usage ?

usage

> what is the error you are getting ?

The views are not founded

> Extra Info "attaching a screen shot would be very helpful"

<img width="1279" alt="Screen Shot 2020-10-01 at 11 21 24 AM" src="https://user-images.githubusercontent.com/18368441/94814361-e77adf80-0401-11eb-90f5-4c6f7747de56.png">

> Do You Know A Solution For this Issue ?

No

**Comment by ctf0** [comment]
this is an issue with setup, have u completed all the setup steps ?

**Comment by AhmedBenCheikh** [comment]
yes i complete all setup steps

<img width="286" alt="Screen Shot 2020-10-01 at 6 37 26 PM" src="https://user-images.githubusercontent.com/18368441/94831235-2b2b1480-0415-11eb-8c04-cfe04442eba9.png">

**Comment by ctf0** [comment]
am not sure what to make from the screen shot, but ur error means the app cant find the route.

plz chk the rdme and make sure all the steps are meet.

**Comment by AhmedBenCheikh** [comment]
ok i will do, thx for your reply
