### ISSUE TITLE
Implementation without Vue

### ISSUE THREAD

**Issue by gRoberts84** [ctf0/Laravel-Media-Manager#162]
Hi there,

It may be the lack of coffee (or whisky) today but I've spent a few hours now totally racking my brains on how to integrate Media Manager into my Bootstrap 4 based admin panel that will allow users to select media in a similar fashion to how Wordpress would.

Totally misunderstanding the requirement to heavily bake Vue into the system, when all I need is a modal that I can load the media manager and then accept javascript events to pick up on any actions within Media Manager.

Your Modal documentation assumes I will be using Vue a lot, however my goal is to totally avoid using Vue at all costs. 

Any suggestions?

**Comment by ctf0** [comment]
unfortunately the whole thing is built on vue + we use bulma for styling.
