### ISSUE TITLE
Preview of image files

### ISSUE THREAD

**Issue by wei-jinn** [ctf0/Laravel-Media-Manager#163]
Greetings. I just installed your media manager. Thanks for the awesome features and visual design. Everything works fine except the preview of image(jpg, svg format) does not show. What can I do to solve this issue?
![image](https://user-images.githubusercontent.com/45649909/95932642-f9e01a80-0dfe-11eb-84b5-07798ff1510f.png)

**Comment by ctf0** [comment]
there is a template for the tickets, plz use it.

anyhow, without errors to debug there isnt much to say but i believe ur issue is related to running on localhost, so make sure your `APP_URL` is `localhost:8000` or whatever port u r using for ur app.

**Comment by wei-jinn** [comment]
Thanks！
