### ISSUE TITLE
Can't resolve download.min

### ISSUE THREAD

**Issue by cpuzzuol** [ctf0/Laravel-Media-Manager#17]
When I go to run "npm run watch" the following error turns up in my console:

ERROR in ./resources/assets/vendor/MediaManager/js/components/mixins/utils.js
Module not found: Error: Can't resolve './../../vendor/download.min' in '/Users/cpuzzuol/laravel/mediaserve/resources/assets/vendor/MediaManager/js/components/mixins'

And indeed I don't see the download.min file in the specified directory.

This is using a fresh install of Laravel 5.5.

**Comment by ctf0** [comment]
some how i missed it, plz install https://github.com/ctf0/Laravel-Media-Manager/tree/master/src/resources/assets/js/vendor manually.

it will be avail from next release, 
also if you found any mis-behaves while using the manager or difficulties while installing plz dont hesitate to open a ticket. thanx for the headsup.
