### ISSUE TITLE
[BUG] npm errors when using laravel mix v6

### ISSUE THREAD

**Issue by ChristianC1123** [ctf0/Laravel-Media-Manager#170]
> What version of Laravel are you using? (nothing lower than v6).

Version 8.20.1

> is it an issue related to installation or usage ?

on installation

> what is the error you are getting ?

on npm run watch I receive a lot of errors.
plyr and cropperjs no stylesheet to import. -> I've fixed a part with npm installation and changed the source folder

> Extra Info "attaching a screen shot would be very helpful"

![image](https://user-images.githubusercontent.com/71841871/103180684-5d270800-4898-11eb-92d6-345a8515b0a8.png)

> Do You Know A Solution For this Issue ?

The Problems are only from your needed addons. Need to import them in composer.json?

**Comment by ctf0** [comment]
whats the manager version ?

**Comment by ctf0** [comment]
this is mostly related to the new version `3.8` which use laravel mix v6 https://github.com/ctf0/Laravel-Media-Manager/releases/tag/v3.8.0

**Comment by ChristianC1123** [comment]
Yes, it's about laravel mix 6. After update it works. 
Your great.
