### ISSUE TITLE
[BUG] ReferenceError: EventHub is not defined

### ISSUE THREAD

**Issue by ChristianC1123** [ctf0/Laravel-Media-Manager#171]
Laravel version `php artisan -v`: 8.20.1
Manager version `composer info ctf0/media-manager`: v 3.8.0

> is it an issue related to installation or usage ?

usage Manager from a Modal

> what is the error you are getting ?

It doesn't work right. I receive a lot of errors in my browser console.
-> ReferenceError: EventHub is not defined
-> [Vue warn]: Error in mounted hook: "ReferenceError: EventHub is not defined"
-> 

> Extra Info "attaching a screen shot would be very helpful"

...
![image](https://user-images.githubusercontent.com/71841871/103282546-6d450180-49d6-11eb-97cf-620022bd8366.png)

> Do You Know A Solution For this Issue ?

.

**Comment by ctf0** [comment]
plz note that tickets are not a **how to area**, check the [demo repo](https://github.com/ctf0/demos/tree/media-manager) for the basic setup & wiki for any further details.
