### ISSUE TITLE
[Feature] Media Modal: Display a select button when image is selected

### ISSUE THREAD

**Issue by thanhtung2693** [ctf0/Laravel-Media-Manager#175]
Hi,
In modal view, when the user select an image, can we have some kind of indicators for user to know that they can select that image instead of clicking on the close icon.

Temporarily I added a button when user select an image, hope this feature will be added in the future.
Many thanks :).

![image](https://user-images.githubusercontent.com/4317955/105145510-70449500-5b31-11eb-937b-e6b1a13cf564.png)

**Comment by ctf0** [comment]
most the time i use the modal with an editor & for the btn yes its a good UX but i prefer to keep it to the wrapping component to decide if any extra elements should show up or not instead of enforcing it all around,
more of an opt-in option instead of opt-out.
