### ISSUE TITLE
[BUG] Error in mounted hook: dropzone is not a constructor

### ISSUE THREAD

**Issue by emielmolenaar** [ctf0/Laravel-Media-Manager#178]
Laravel version `php artisan -v`: 7.30.3
Manager version `composer info ctf0/media-manager`: v3.8.2
Laravel mix version: 6

> is it an issue related to installation or usage ?

Usage

> what is the error you are getting ?

Error in mounted hook: "TypeError: dropzone__WEBPACK_IMPORTED_MODULE_1___default(...) is not a constructor"

> Extra Info "attaching a screen shot would be very helpful"

https://imgur.com/1CAHsFh

> Do You Know A Solution For this Issue ?

Nope

**Comment by ctf0** [comment]
can u try with the demo repo ?

**Comment by emielmolenaar** [comment]
I'm sorry, what do you mean actually?

**Comment by ctf0** [comment]
i mean can u reproduce this issue with the demo repo ?

**Comment by emielmolenaar** [comment]
I switched to another dev box and had no problems there. I guess it has something to do with versions of different packages or me not installing a dependency... Will figure out what happened whem I am back at the dev box where the issue occured.

**Comment by emielmolenaar** [comment]
All right, figured it out. The problem was a broken build of dropzone: https://github.com/dropzone/dropzone/blob/main/CHANGELOG.md#573-retracted . Upgraded Dropzone, fixing the issue.

**Comment by ctf0** [comment]
awesome
