### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by devops1107** [ctf0/Laravel-Media-Manager#179]
Laravel version `php artisan -v`:
Manager version `composer info ctf0/media-manager`:

> is it an issue related to installation or usage ?
installation 
...

> what is the error you are getting ?
I have run all command as fine and cant run 'npm run watch'
...

> Extra Info "attaching a screen shot would be very helpful"

...

> Do You Know A Solution For this Issue ?
I cant find solution

app.js

webpack.mix.js
...

**Comment by ctf0** [comment]
what exactly is the issue ?

plz use the demo repo to reproduce ur issue.

**Comment by devops1107** [comment]
I have use 3.6.5 with laravel 5.8 and laravel-mix 5.0
C:\xampp\htdocs>npm run watch

> @ watch C:\xampp\htdocs
> npm run development -- --watch


> @ development C:\xampp\htdocs
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

 10% building modules 1/1 modules 0 active
Webpack is watching the files…

 13% building modules 27/38 modules 11 active ...odules\vue-notif\src\Notification.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 95% emitting

 ERROR  Failed to compile with 2 errors                                                                                                                                                                                       5:01:16 PM

These dependencies were not found:

* worker-loader!../webworkers/db in ./resources/assets/vendor/MediaManager/js/modules/cache.js
* worker-loader!../webworkers/audio in ./resources/assets/vendor/MediaManager/js/modules/media_player.js

To install them, you can run: npm install --save worker-loader!../webworkers/db worker-loader!../webworkers/audio
                                                                                                  Asset       Size  Chunks                    Chunk Names
     images/vendor/vue-notif/src/icons/baseline-track_changes-24px.svg?d2bfd4e80dd3cbcac050c28120fcac43  572 bytes          [emitted]
      images/vendor/vue-notif/src/icons/baseline-check_circle-24px.svg?b7860a7d972c8792a7fb7723054eebcc  267 bytes          [emitted]
         images/vendor/vue-notif/src/icons/baseline-live_help-24px.svg?960797342bb185c849a8334a530ff2b5  440 bytes          [emitted]
images/vendor/vue-notif/src/icons/baseline-power_settings_new-24px.svg?7c183e3ca58f7ee892f4373bb49bf9f8  358 bytes          [emitted]
         images/vendor/vue-notif/src/icons/baseline-add_alert-24px.svg?0d11f840e89076f0bca204e72c2641ac  412 bytes          [emitted]
             images/vendor/vue-notif/src/icons/baseline-error-24px.svg?0234efef104d9bb47b670372282ce34b  246 bytes          [emitted]
                                                                                             /js/app.js    2.49 MB       0  [emitted]  [big]  /js/app
                                                                                           /css/app.css     226 kB       0  [emitted]         /js/app
                                                                  /assets/vendor/MediaManager/style.css     114 kB       0  [emitted]         /js/app

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"he
lpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-focuspoint-component/src/components/FocusPoint.vue
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "C:\\xampp\\htdocs\\node_modules\\vue-focuspoint-component\\.babelrc" at 0, attempted to resolve relative to "C:\\xampp\\htdocs\\node_modules\\vue-
focuspoint-component"
    at C:\xampp\htdocs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\xampp\htdocs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\xampp\htdocs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\xampp\htdocs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\xampp\htdocs\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\xampp\htdocs\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\xampp\htdocs\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\xampp\htdocs\node_modules\babel-loader\lib\index.js:50:20)
    at C:\xampp\htdocs\node_modules\babel-loader\lib\fs-cache.js:118:18
    at ReadFileContext.callback (C:\xampp\htdocs\node_modules\babel-loader\lib\fs-cache.js:31:21)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13)
 @ ./node_modules/vue-focuspoint-component/src/components/FocusPoint.vue 4:21-350
 @ ./node_modules/vue-focuspoint-component/src/index.js
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers"
:false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/vendor/MediaManager/js/components/utils/upload-preview.vue
 @ ./resources/assets/vendor/MediaManager/js/components/utils/upload-preview.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers"
:false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/vendor/MediaManager/js/components/manager.vue
 @ ./resources/assets/vendor/MediaManager/js/components/manager.vue
 @ ./resources/assets/vendor/MediaManager/js/manager.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/vendor/MediaManager/sass/manager.scss

ERROR in ./resources/assets/vendor/MediaManager/js/modules/cache.js
Module not found: Error: Can't resolve 'worker-loader' in 'C:\xampp\htdocs\resources\assets\vendor\MediaManager\js\modules'
 @ ./resources/assets/vendor/MediaManager/js/modules/cache.js 1:0-54
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers"
:false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/vendor/MediaManager/js/components/manager.vue
 @ ./resources/assets/vendor/MediaManager/js/components/manager.vue
 @ ./resources/assets/vendor/MediaManager/js/manager.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/vendor/MediaManager/sass/manager.scss

ERROR in ./resources/assets/vendor/MediaManager/js/modules/media_player.js
Module not found: Error: Can't resolve 'worker-loader' in 'C:\xampp\htdocs\resources\assets\vendor\MediaManager\js\modules'
 @ ./resources/assets/vendor/MediaManager/js/modules/media_player.js 2:0-60
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers"
:false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/vendor/MediaManager/js/components/manager.vue
 @ ./resources/assets/vendor/MediaManager/js/components/manager.vue
 @ ./resources/assets/vendor/MediaManager/js/manager.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/vendor/MediaManager/sass/manager.scss

ERROR in ./node_modules/fuse.js/dist/fuse.esm.js
Module parse failed: Unexpected token (271:2)
You may need an appropriate loader to handle this file type.
|
| var Config = {
|   ...BasicOptions,
|   ...MatchOptions,
|   ...FuzzyOptions,
 @ ./resources/assets/vendor/MediaManager/js/manager.js 10:14-32
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/vendor/MediaManager/sass/manager.scss
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'




- webpack.mix.js


let mix = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

// MediaManager
mix.sass('resources/assets/vendor/MediaManager/sass/manager.scss', 'public/assets/vendor/MediaManager/style.css')
    .copyDirectory('resources/assets/vendor/MediaManager/dist', 'public/assets/vendor/MediaManager')







- app.js






import Vue from 'vue'


require('../vendor/MediaManager/js/manager.js')


new Vue({
    el: '#app'
})

**Comment by ctf0** [comment]
u r using a year old release which i dont have any recollection of what its state was, sorry cant help.
