### ISSUE TITLE
npm run dev is failing

### ISSUE THREAD

**Issue by mckenzieflavius** [ctf0/Laravel-Media-Manager#18]
`npm run dev` is failing saying it cant find certain files. I've literally no idea why its doing this.
below is a part of the error im getting.

`ERROR in ./resources/assets/vendor/MediaManager/js/manager.js
Module not found: Error: Can't resolve 'keycode' in 'C:\Users\mckenzie.flavius\D                                                                          ocuments\Applications\IKDevelopment\Templates\Blogging\5.5\resources\assets\vend                                                                          or\MediaManager\js'
 @ ./resources/assets/vendor/MediaManager/js/manager.js 11:17-35
 @ multi ./resources/assets/vendor/MediaManager/js/manager.js

ERROR in ./resources/assets/vendor/MediaManager/js/manager.js
Module not found: Error: Can't resolve 'vue-clipboard2' in 'C:\Users\mckenzie.fl                                                                          avius\Documents\Applications\IKDevelopment\Templates\Blogging\5.5\resources\asse                                                                          ts\vendor\MediaManager\js'
 @ ./resources/assets/vendor/MediaManager/js/manager.js 15:8-33
 @ multi ./resources/assets/vendor/MediaManager/js/manager.js

ERROR in ./resources/assets/vendor/MediaManager/js/manager.js
Module not found: Error: Can't resolve 'vue-notif' in 'C:\Users\mckenzie.flavius                                                                          \Documents\Applications\IKDevelopment\Templates\Blogging\5.5\resources\assets\ve                                                                          ndor\MediaManager\js'
 @ ./resources/assets/vendor/MediaManager/js/manager.js 26:32-52
 @ multi ./resources/assets/vendor/MediaManager/js/manager.js

ERROR in ./resources/assets/vendor/MediaManager/js/manager.js
Module not found: Error: Can't resolve 'vue-tippy' in 'C:\Users\mckenzie.flavius                                                                          \Documents\Applications\IKDevelopment\Templates\Blogging\5.5\resources\assets\ve                                                                          ndor\MediaManager\js'
 @ ./resources/assets/vendor/MediaManager/js/manager.js 13:8-28
 @ multi ./resources/assets/vendor/MediaManager/js/manager.js

ERROR in ./resources/assets/vendor/MediaManager/js/manager.js
Module not found: Error: Can't resolve 'vue-touch' in 'C:\Users\mckenzie.flavius                                                                          \Documents\Applications\IKDevelopment\Templates\Blogging\5.5\resources\assets\ve                                                                          ndor\MediaManager\js'
 @ ./resources/assets/vendor/MediaManager/js/manager.js 17:15-35
 @ multi ./resources/assets/vendor/MediaManager/js/manager.js

ERROR in ./resources/assets/vendor/MediaManager/js/manager.js
Module not found: Error: Can't resolve 'vue2-filters' in 'C:\Users\mckenzie.flav                                                                          ius\Documents\Applications\IKDevelopment\Templates\Blogging\5.5\resources\assets                                                                          \vendor\MediaManager\js'
 @ ./resources/assets/vendor/MediaManager/js/manager.js 14:8-31
 @ multi ./resources/assets/vendor/MediaManager/js/manager.js

ERROR in ./resources/assets/vendor/MediaManager/js/manager.js
Module not found: Error: Can't resolve 'vuemit' in 'C:\Users\mckenzie.flavius\Do                                                                          cuments\Applications\IKDevelopment\Templates\Blogging\5.5\resources\assets\vendo                                                                          r\MediaManager\js'
 @ ./resources/assets/vendor/MediaManager/js/manager.js 10:18-35
 @ multi ./resources/assets/vendor/MediaManager/js/manager.js`

**Comment by ctf0** [comment]
have u installed any of the [js dependencies](https://github.com/ctf0/Laravel-Media-Manager#usage) ?

basically all the errors u r getting means that non of those packages is installed.

**Comment by mckenzieflavius** [comment]
Ooh I wasn’t aware I had to install them myself I thought they would have been pulled in along with the package, should I install them all through npm? (Node isn’t my strong point)

**Comment by ctf0** [comment]
yeap, no worries as u just need to install the packages and we already take care of everything else.
