### ISSUE TITLE
[Question] Problems with Vue on 3.6.7 version.

### ISSUE THREAD

**Issue by anonunder** [ctf0/Laravel-Media-Manager#181]
Hello,

I did all what is written in readme, but I am facing problems with VUE. Also, this is the first time using vue..

I am using 3.6.7  because my app is on 5.8 so i can't use newer version. 

[Media manager 3.6.7](https://github.com/ctf0/Laravel-Media-Manager/tree/v3.6.7)

In console it gave me two errors: [Error in console](https://prnt.sc/1010741) with BLANK page but when i click on page source i can see that the page is rendered: [Page source](https://pastebin.com/N9Wxw6Q0)

I think I am stuck at this:

```js
// app.js
window.Vue = require('vue')

// Laravel < v5.7
require('../vendor/MediaManager/js/manager')
// Laravel > v5.7
// require('../assets/vendor/MediaManager/js/manager')

new Vue({
    el: '#app'
})
```

Where should i put it ? If I put it in media.blade.php i got Require is not a function. If i include require, there is another error
`Module name "vue" has not been loaded yet for context: _. Use require([])`

If i use require(['vue']) i got like, 20 errors..

What is the problem here? Previous steps are completed succesffully.

**Comment by ctf0** [comment]
as the doc says
> add this one liner to your main js file

so in most case it will be `app.js`
