### ISSUE TITLE
wysiwyg Editor Which works with this package?

### ISSUE THREAD

**Issue by Zubair-Iftikhar** [ctf0/Laravel-Media-Manager#182]
in documentation tinymce given but now code is not working...any Editor Which works properly with this package?

**Comment by ctf0** [comment]
u can use https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-With-Any-WYSIWYG-Editor as a guideline for ur editor integration, the first lines shows whats needed

```
- depends on your editor of choice, the implementation may vary, but here is what you need to do
  - have a way to trigger the manager modal button $('.__Inmodal-editor').click()
  - listen for when a file is selected and insert it into your editor EventHub.listen('file_selected', (path) => {...})
```
