### ISSUE TITLE
[Question] npm run watch with errors

### ISSUE THREAD

**Issue by GrytsenkoAndrey** [ctf0/Laravel-Media-Manager#185]
You can see the list bellow:

![изображение](https://user-images.githubusercontent.com/63291871/112729154-6f662000-8f33-11eb-8218-f07e20a21b42.png)

any idea why it's happened?

**Comment by ctf0** [comment]
what version r u using ?, if this is a bug plz create a bug ticket using the template.

**Comment by GrytsenkoAndrey** [comment]
the latest one (v 3.8.6)

**Comment by ctf0** [comment]
can u repro with the demo repo ?

**Comment by GrytsenkoAndrey** [comment]
I can try demo repo but actually I don't need a demo repo - I went step by step as it described in docs because I want to add it to my project.
Demo project (repo) won't help me.

**Comment by ctf0** [comment]
i cant help u with ur current situation.
