### ISSUE TITLE
Can this be used for user read-only and admin upload?[Question]

### ISSUE THREAD

**Issue by niels-numbers** [ctf0/Laravel-Media-Manager#186]
Hey, thank you for this great manager.

I have an application with users and admins. I need a file-manager in a way, that users can only download and see content, and admins can upload content. In addition, I have different user groups and I want them to restrict each user group to a specific folder.

Restricting user groups to a folder seems to be possible via https://github.com/ctf0/Laravel-Media-Manager/wiki/Restrict-Access-To-Path

But is the other feature also feasible? In addition to give read/write access, I would like to make sure that users with read acces only don't see delete or upload options. Is it possible? If not, could you point me to a direction what needs to be changed? Do you have a extra repo for your vue files?

**Comment by ctf0** [comment]
>  In addition to give read/write access, I would like to make sure that users with read access only don't see delete or upload options

- for this we can add a couple of new props to allow/disallow the manager features 
- or maybe have something like a read-only mode where we basically disable the top toolbar.

> Do you have a extra repo for your vue files?

sadly not but for now all the manager js files are under https://github.com/ctf0/Laravel-Media-Manager/tree/master/src/resources/assets/js
