### ISSUE TITLE
Request Upload Progress Display improvement[Feature]

### ISSUE THREAD

**Issue by jasperf** [ctf0/Laravel-Media-Manager#187]
You wrote about _request progress "axios progress reports ain't accurate"_ already, but mentioned anyone wanting to talk about the issues you would like to work on in a new issue/ feature request so here I go.

When I currently upload 5-10 images in my Laravel / Vue / Axios app it states 100% done pretty much right away while we are not done uploading the images. Any ideas how we could check to make sure all images are uploaded and resizing done? 

We do resize before upload, but this is done in the browser before the upload is taken care of. So I assume the 100% is simply shown before all uploads are done. Do you already have a better check to see all x images are uploaded? Or is there a more accurate way to show 20% done when 2 of 10 images have been uploaded?

**Comment by ctf0** [comment]
the progress is handled via dz https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/assets/js/modules/upload.js

u can also check https://ctf0.wordpress.com/2017/07/16/how-to-use-multiple-file-upload-in-dropzone/ which i have written abit about how dz manager the upload progress

to get the expected progress, u will have to disable the chunk upload and inform dz to upload files one by one which is not recommended
