### ISSUE TITLE
[BUG] global search issues

### ISSUE THREAD

**Issue by ChristianC1123** [ctf0/Laravel-Media-Manager#188]
Laravel version `php artisan -v`: 8.20.1
Manager version `composer info ctf0/media-manager`:
name     : ctf0/media-manager
descrip. : A Media Manager Built With Vuejs & Laravel
keywords : ctf0, gui, laravel, manager, media, mediamanager
versions : * v3.8.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://github.com/ctf0/Laravel-Media-Manager
source   : [git] https://github.com/ctf0/Laravel-Media-Manager.git 5cba9e97175ca41f6720ad77ca637a8e7d3bc18c
dist     : [zip] https://api.github.com/repos/ctf0/Laravel-Media-Manager/zipball/5cba9e97175ca41f6720ad77ca637a8e7d3bc18c 5cba9e97175ca41f6720ad77ca637a8e7d3bc18c
path     : C:\wamp64\www\Arbeitsanweisung\vendor\ctf0\media-manager
names    : ctf0/media-manager

support
issues : https://github.com/ctf0/Laravel-Media-Manager/issues
source : https://github.com/ctf0/Laravel-Media-Manager/tree/v3.8.0

autoload
psr-4
ctf0\MediaManager\ => src

requires
ctf0/package-changelog *
illuminate/support >=7.0 <9.0
jhofm/flysystem-iterator ^2.2
maennchen/zipstream-php >=1.0

suggests
league/flysystem-cached-adapter Required to use the Flysystem cache (~1.0).

> is it an issue related to installation or usage ? 

usage

> what is the error you are getting ?

on global search, I receive an white page with an editable field, without any results
on console: Failed to load resource: the server responded with a status of 404 (Not Found)      [object%20Module]:1

> Extra Info "attaching a screen shot would be very helpful"

![Screenshot 2021-05-04 133750](https://user-images.githubusercontent.com/71841871/116998066-f69a7680-acdd-11eb-8757-cb978026e4c4.png)
![Screenshot 2021-05-04 134151](https://user-images.githubusercontent.com/71841871/116998458-8b9d6f80-acde-11eb-827f-d3e5836f6621.png)

> Do You Know A Solution For this Issue ?

no

**Comment by ctf0** [comment]
i cant tell what exactly is the issue, can u repro with the demo repo ?

**Comment by ChristianC1123** [comment]
I've tried with your demo. It looks a little bit different but doesn't work, too.
![Screenshot 2021-05-06 153714](https://user-images.githubusercontent.com/71841871/117307609-01414100-ae81-11eb-91c5-4d69b03dfb2b.png)


On the first click "global search" I receive the 404 in my console.
On the second click "global search" it shows this black screen with an input field in the left upper corner.

I receive no results.

**Comment by ctf0** [comment]
for the `Failed to load resource: the server responded with a status of 404 (Not Found)` error this is related to the vue-loader https://github.com/JeffreyWay/laravel-mix/issues/2709

as for other issues, plz try again with the latest commit, it should be fixed.

**Comment by ChristianC1123** [comment]
Now, it works fine in your demo! Thank you! You're the best.
On my project I've got some trouble now with vue-awesome on run watch, but I think it's not your part.
