### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by proibo** [ctf0/Laravel-Media-Manager#189]
Laravel version `php artisan -v`:
Manager version `composer info ctf0/media-manager`:
versions : * v3.8.7

> is it an issue related to installation or usage ?
installation
...

> what is the error you are getting ?
Not Found
The requested resource /media was not found on this server.
...

> Extra Info "attaching a screen shot would be very helpful"
![image](https://user-images.githubusercontent.com/44711216/117871535-292c0c80-b2a6-11eb-803c-8ae5a445f5c3.png)

...

> Do You Know A Solution For this Issue ?
no
...

**Comment by ctf0** [comment]
plz try with the demo repo
