### ISSUE TITLE
Class 'Form' not found!

### ISSUE THREAD

**Issue by eamirgh** [ctf0/Laravel-Media-Manager#19]
Class 'Form' not found in path-to-source\resources\views\vendor\MediaManager\_manager.blade.php
bad solution is
Register facades by adding these two lines in the aliases array:
```
'Form'=> 'Illuminate\Html\FormFacade',
'HTML'=> 'Illuminate\Html\HtmlFacade',
```

**Comment by ctf0** [comment]
because we use https://packagist.org/packages/laravelcollective/html , will be removed in next release
