### ISSUE TITLE
[Question] from modal, different entry folder

### ISSUE THREAD

**Issue by ChristianC1123** [ctf0/Laravel-Media-Manager#190]
Hello,
we've got different folders, like music, pictures, videos.
Is it possible to manage the entry point, if you want to chose a file from the music folder?
And on an other point you want to select a video from the video folder.

It will be a little bit easier to start in the right folder.

Thank you for this media-manager.

**Comment by ctf0** [comment]
am not sure what exactly u r after, can u elaborate.
