### ISSUE TITLE
[Question] Media from Modal - entry folder

### ISSUE THREAD

**Issue by ChristianC1123** [ctf0/Laravel-Media-Manager#193]
Hello,

I use the Manager from a Modal and I use cover and links on the page.

Is it possible to overwrite the entry folder on local storage only for the links?

![Screenshot 2021-06-21 154958](https://user-images.githubusercontent.com/71841871/122773142-5f4aac00-d2a8-11eb-948e-2d9756affb60.png)

Thanks for your help.

**Comment by ctf0** [comment]
what u mean ?

**Comment by ChristianC1123** [comment]
I
![Screenshot 2021-06-22 090357](https://user-images.githubusercontent.com/71841871/122879535-4c33ec80-d339-11eb-8c7f-b0f678bc1006.jpg)

Is it possible to set the initial folder for the media manager? I use the component in two places and want to set a different initial folder for each.

**Comment by ctf0** [comment]
no its not possible, currently u can only restrict the paths for each.

**Comment by ChristianC1123** [comment]
Thank you, I will tryAm 22.06.2021 12:03 schrieb Muah ***@***.***>:
doesnt something like
<media-modal :restrict="{
   'path' => 'users/admin/pdfs'
}" etc..></media-modal>
work for u ?

**Comment by ChristianC1123** [comment]
Here is my feedback

Doesn't work.
`<media-modal item="links" :name="inputName" :multi="false" :restrict="{
                path: 'Zusatzdokumente'
             }"></media-modal>`



And your snipped 

`<media-modal item="links" :name="inputName" :multi="false" :restrict="{
                'path' => 'Zusatzdokumente'
             }"></media-modal>`

shows me this error in my browser console

`[Vue warn]: Error compiling template:

invalid expression: Unexpected token '=>' in

    {
                'path' => 'Zusatzdokumente'
             }

  Raw expression: :restrict="{
                'path' => 'Zusatzdokumente'
             }"


2513|              
2514|              <media-modal item="cover" :name="inputName"></media-modal>
2515|              <media-modal item="links" :name="inputName" :multi="false" :restrict="{
   |                                                                         ^^^^^^^^^^^^
2516|                  'path' => 'Zusatzdokumente'
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2517|               }"></media-modal>
   |  ^^^^^^^^^^^^^^^

(found in <Root>)`

**Comment by ctf0** [comment]
plz make a repo so i can reproduce with

**Comment by ChristianC1123** [comment]
https://github.com/ChristianC1123/mediamanager_test

**Comment by ctf0** [comment]
@ChristianC1123 ur repo is incomplete, plz test ur issue with the [demo repo](https://github.com/ctf0/demos/tree/media-manager) and reply back if the issue still exists.
