### ISSUE TITLE
[Question]modal doesn't work

### ISSUE THREAD

**Issue by Yoji** [ctf0/Laravel-Media-Manager#198]
Hello, there is a problem, I hope you can help. Did everything exactly like here:
https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal

And added css. But the result was as follows:
![2022-02-04_21-45-06](https://user-images.githubusercontent.com/6072785/152585407-2e3616ef-0e65-4b81-9c68-fe23ea724ba6.png)

Where did I make a mistake?

**Comment by ctf0** [comment]
can u reproduce with the demo repo?

**Comment by Yoji** [comment]
Unfortunately I can't give a demo repo
If I add manually:
//cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css

And replace form with div

Then the modal window starts working

**Comment by ctf0** [comment]
i meant this demo repo https://github.com/ctf0/demos/tree/media-manager
