### ISSUE TITLE
I want to translate the package in french

### ISSUE THREAD

**Issue by christmichee123** [ctf0/Laravel-Media-Manager#199]
Hello Sir, your package is great. But i want to translate the render on page media in french

**Comment by ctf0** [comment]
yes plz, i would appreciate that

**Comment by christmichee123** [comment]
Apparently we didn't understand each other. I wanted to know how it's possible to translate the package into French.
but tell me is it possible to translate it thanks to the lang file?

**Comment by ctf0** [comment]
u need to translate this file https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/lang/en/messages.php

**Comment by christmichee123** [comment]
Ok great
