### ISSUE TITLE
[BUG] Laravel 5.8 and Media Manager 3.6.7

### ISSUE THREAD

**Issue by anonunder** [ctf0/Laravel-Media-Manager#202]
Laravel version `php artisan -v`:
Manager version `composer info ctf0/media-manager`:

> is it an issue related to installation or usage ?

Usage

> what is the error you are getting ?

If you are using "drag and drop" on dropzone, request is empty. Path is not send, also random_names too.

> Extra Info "attaching a screen shot would be very helpful"

It should like this: https://prnt.sc/Xb_hjulPuQX7 
It looks like this: https://prnt.sc/eL8RxtvwQS3q

It works when I click to upload, just drag and drop doesnt work.

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
thats a 2yrs old release and unfortently i cant test it.

**Comment by anonunder** [comment]
> thats a 2yrs old release and unfortently i cant test it.

Yes I know and I need to fix it. My project is 3 years old and I don't have time to upgrade it to newer version. Any kind of help will be good..

**Comment by ctf0** [comment]
sadly i cant help.
