### ISSUE TITLE
Blank Screen on /media

### ISSUE THREAD

**Issue by AlekoB1977** [ctf0/Laravel-Media-Manager#203]
Hello,

I have followed the installation and configuration guide, but still, have the same issue with the blank screen when I go to "/media" URL.

My PHP version is 7.3.31 (cli) with Laravel 8.

Any suggestions? Or is it just a BUG?

Thanks

**Comment by ctf0** [comment]
check the dev tools of ur browser

**Comment by AlekoB1977** [comment]
I have and also checked the source code, which is loaded BTW. 

I have two warnings in the console:
[Vue warn]: Unknown custom element: "my-notification" - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in "Root")

[Vue warn]: Unknown custom element: "media-manager" - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in "Root")

**Comment by ctf0** [comment]
can u repro with the [demo](https://github.com/ctf0/demos/tree/media-manager) repo ?

**Comment by AlekoB1977** [comment]
Here it is: https://github.com/AlekoB1977/media-manager

**Comment by AlekoB1977** [comment]
All Fixed now. It was a mistake on my part, I have not checked the mix file
