### ISSUE TITLE
Not works with laravel 9.12.1 [BUG]

### ISSUE THREAD

**Issue by m4tt86** [ctf0/Laravel-Media-Manager#204]
Laravel version `php artisan -v`: 9.12.1
Manager version `composer info ctf0/media-manager`:

> is it an issue related to installation or usage ?

Installation

> what is the error you are getting ?

Problem 1
    - ctf0/media-manager[v3.8.0, ..., v3.8.7] require illuminate/support >=7.0 <9.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires ctf0/media-manager ^3.8 -> satisfiable by ctf0/media-manager[v3.8.0, ..., v3.8.7].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require ctf0/media-manager:*" to figure out if any version is installable, or "composer require ctf0/media-manager:^2.1" if you know which you need.

If tried also with "ctf0/media-manager": "dev-master" on composer.json but I receive the following error:

Problem 1
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.19) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.19) does not satisfy that requirement.
    - Root composer.json requires ctf0/media-manager dev-master -> satisfiable by ctf0/media-manager[dev-master].
    - Conclusion: don't install laravel/framework v9.12.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.13.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.14.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.14.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.15.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.16.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.17.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.18.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.11.0 (conflict analysis result)
    - ctf0/media-manager dev-master requires illuminate/support >=7.0 <9.0 -> satisfiable by illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.11.0, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.11 -> satisfiable by laravel/framework[v9.11.0, ..., 9.x-dev].

**Comment by ctf0** [comment]
yes its not supported yet
