### ISSUE TITLE
[Question] S3 error after upgrading laravel 9

### ISSUE THREAD

**Issue by AmityTek** [ctf0/Laravel-Media-Manager#206]
I have this error after install laravel 9

![image](https://user-images.githubusercontent.com/18656702/212665831-5ea58995-9d62-4e9f-a47e-587806e19ec7.png)

My require is composer.json:

 "require": {
        "aws/aws-sdk-php": "*",
        "ctf0/media-manager": "*",
        "fideloper/proxy": "*",
        "fruitcake/laravel-cors": "^3.0",
        "guzzlehttp/guzzle": "*",
        "laravel/framework": "^9.0",
        "laravel/tinker": "*",
        "league/flysystem-aws-s3-v3": "*"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "spatie/laravel-ignition": "^1.0",
        "fakerphp/faker": "*",
        "mockery/mockery": "*",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "*"
    },

**Comment by ctf0** [comment]
i havent quite tested the latest update with all the drivers thats also why i havent tagged a new realease yet.

anyway this seems related to s3 driver, can u debug the issue more and either make a PR with the fix or at least give me some context to start with ?

also can u plz use the ticket template ?

**Comment by AmityTek** [comment]
Thank you for the quick answer !
I canceled my change and will try later, I will provide PR if I can solve it !
