### ISSUE TITLE
Supports images in the cloud? 

### ISSUE THREAD

**Issue by bartclaeys** [ctf0/Laravel-Media-Manager#209]
Does this package support images in the cloud? Obviously file manipulations won't be able to be executed when the file lives in the cloud, but I wonder whether the package otherwise works with such images.

**Comment by ctf0** [comment]
it works with laravel supported filesystems (i only tested it out with "local / s3 / google drive").

but if u have a problem with a specific adaptor, tell me the error u r getting and maybe i could help.
