### ISSUE TITLE
got directory error on laravel 5.5 fresh install 

### ISSUE THREAD

**Issue by emtized** [ctf0/Laravel-Media-Manager#21]
Hi 

 i got below error for installation on new laravel 5.5 fresh one after : 

composer require ctf0/media-manager

In Finder.php line 539:
                                                                                
  The "C:\xampp\htdocs\upload\public\assets/vendor/MediaManager/patterns" directory does not exist.
                                                                                

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by ctf0** [comment]
have u published the assets ?

**Comment by emtized** [comment]
we have to publish assets before composer require ?

**Comment by ctf0** [comment]
ofcourse not , but the fact that u r getting this error is really weird.

**Comment by emtized** [comment]
my problem is that i got this error as soon as i enter composer require command in terminal 
 You can test it on laravel 5.5 by create a new project with composer command then require your project 
you will see this error

**Comment by ctf0** [comment]
okay found the problem, plz try again with the latest release.

again thanks for the heads up, if you found any other issues plz report them as well.

**Comment by emtized** [comment]
@ctf0  Thanks  
Sure i will
