### ISSUE TITLE
Issue when project run in server

### ISSUE THREAD

**Issue by ejklock** [ctf0/Laravel-Media-Manager#22]
I Have a new issue when i put de project to run in ubuntu server

the error happens when the script calls /media/files

Details:

{message: "could not find driver (SQL: select "path" from "locked")",…}
exception
:
"Illuminate\Database\QueryException"
file
:
"/var/www/media/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line
:
664
message
:
"could not find driver (SQL: select "path" from "locked")"
trace
:
[,…]

Has anyone ever experienced this?

**Comment by ejklock** [comment]
Solved!
sudo apt-get install php7.0-sqlite

**Comment by ctf0** [comment]
can u send me a pr with what u need to install sqlite on ubuntu ?

**Comment by ejklock** [comment]
So ... I think it was some installation restriction of standard Ubuntu Server images distributed by the company's IT infrastructure team ...

Anyway, that solved :|

**Comment by ctf0** [comment]
okay, i added a note about this to the rdme and lock/unlock wiki.

thanx for the headsup.

**Comment by ctf0** [comment]
@ejklock sorry to ask, but do u use the manager with a cloud storage ex.`s3` ?
