### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by alexpersegona** [ctf0/Laravel-Media-Manager#26]
I first got an error asking for a missing "MediaManger.sqlite" file. I created that in "storage/logs/." Then I got the following error (which I'm stuck on): 

**SQLSTATE[HY000]: General error: 1 no such table: locked (SQL: select "path" from "locked")**

Can you help me out?

**Steps I took:**

- Installed fresh laravel 5.5 using laravel cli tool
- Installed Laravel-Media-Manager package using composer
- Published assets
- Added "require('./../vendor/MediaManager/js/manager')" to /resources/js/app.js 
- Added NPM dependencies, then did another "npm i"
- Run "composer dump"
- Run "npm run watch"
- Go to valet url: media.test/media ...(get error)

**I'm using:**

- Laravel 5.5
- Laravel valet 2.0.6
- PHP 7.1.10
- Node 9.3.0

Thanks.

**Comment by ctf0** [comment]
the db file should be published automatically when using the publish cmnd, however plz try installing it manually by copying the file @ https://github.com/ctf0/Laravel-Media-Manager/tree/master/src/database

**Comment by Cidro** [comment]
I have the same issue, and notice that the sqlite file was copied to a different folder. Instead of copying it to "storage/logs" it was copied to "storage/log"

**Comment by alexpersegona** [comment]
LOL, was just about to write that.

You're right, it's pointing to "log" instead of "logs."
@cidro, did you get it to work after that? I'm still getting errors.

See: https://ibb.co/kxvDhG

**Comment by Cidro** [comment]
@alexpersegona I had the same error, fixed it using the solution on this issue #16

**Comment by ctf0** [comment]
@Cidro good catch, path fixed

@alexpersegona can u show me the error from the console

**Comment by alexpersegona** [comment]
Originally had the error described above on issue [#16](https://github.com/ctf0/Laravel-Media-Manager/issues/16), but I fixed that using the tips [here](https://ctf0.wordpress.com/2017/09/12/laravel-mix-es6/).

Now here's the latest errors: 
https://ibb.co/fMvzNG
https://ibb.co/j4vc9w

**Comment by ctf0** [comment]
you need to fix the path to the js file, the one in the view file is just a template 
replace `path/to/app.js`
with your app `main.js` file path or whatever you call it

**Comment by alexpersegona** [comment]
You're talking about the view file in the vendor dir "media/vendor/ctf0/media-manager/src/resources/views/media.blade.php"?

**Comment by alexpersegona** [comment]
Never mind I saw it gets published.

Works! Thank you for your mega patience with me!

**Comment by ctf0** [comment]
np, if you think we need to add something to the read me to avoid this confusion, plz do :1st_place_medal:
