### ISSUE TITLE
app.js 404 error on page  http://localhost:8000/path/to/app.js not found

### ISSUE THREAD

**Issue by arunsomant** [ctf0/Laravel-Media-Manager#27]
> What version of Laravel are you using? (nothing lower than v5.4).

5.5

> is it an issue related to installation or usage ?

usage

> what is the error you are getting ?

Failed to load resource: the server responded with a status of 404 (Not Found)   http://localhost:8000/path/to/app.js not found
`
```

**Comment by ctf0** [comment]
this is more related to laravel-mix, still i believe you can fix it using `npm install cross-env --save-dev`

**Comment by ctf0** [comment]
because you should replace 
https://github.com/ctf0/Laravel-Media-Manager/blob/f82b0b1e48f0e7158b075316ce7b3853d605fabf/src/resources/views/media.blade.php#L31 

with your path to `app.js` file or whatever you call it.

**Comment by arunsomant** [comment]
@ctf0 in which file?

**Comment by ctf0** [comment]
under `resources/views/vendor/MediaManager/media.blade.php`
