### ISSUE TITLE
not using npm

### ISSUE THREAD

**Issue by Rndwiga** [ctf0/Laravel-Media-Manager#3]
Hi,

Is it possible to avoid using npm for getting the dependencies and having the asset files pushed to public dir?

**Comment by ctf0** [comment]
i can add a public files yes, however it wont be minified due to an issue with **vueemit** https://github.com/gocanto/vuemit/issues/6#issuecomment-315524595 & laravel mix

**Comment by ctf0** [comment]
done, https://github.com/ctf0/Laravel-Media-Manager/tree/master/src/dist

**Comment by Rndwiga** [comment]
Thanks!
