### ISSUE TITLE
`locked` table not exists

### ISSUE THREAD

**Issue by rohanvakharia** [ctf0/Laravel-Media-Manager#30]
> What version of Laravel are you using? (nothing lower than v5.4).

Laravel 5.6

> is it an issue related to installation or usage ?

Installation

> what is the error you are getting ?

```
Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: 1 no such table: locked (SQL: select "path" from "locked")
```

> Extra Info "attaching a screen shot would be very helpful"

I am using mysql database. I tried running migration command but no success. Even in database as well as in the package code, I am could not to find `locked` table.

**Comment by ctf0** [comment]
the issue u r facing is related to https://github.com/ctf0/Laravel-Media-Manager/wiki/Lock-Files-&-Folder which requires you install sqlite.

i've also updated rdme to emphasis on that.

**Comment by rohanvakharia** [comment]
Thanks. I managed to fix that.

**Comment by ctf0** [comment]
awesome
