### ISSUE TITLE
npm install packages fails

### ISSUE THREAD

**Issue by eugeniregi** [ctf0/Laravel-Media-Manager#32]
Hello I have an issue when install the dependencies with npm 5.6.0 

> What version of Laravel are you using? (nothing lower than v5.4).

5.5.33

> is it an issue related to installation or usage ?

it is an installation issue

> what is the error you are getting ?

```
open
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/code/BDEVMD/node_modules/nyc/node_modules/yargs/node_modules/cliui/package.json.712505904'
npm ERR! enoent This is related to npm not being able to find a file.
```

> Extra Info "attaching a screen shot would be very helpful"

![captura de pantalla de 2018-02-13 21-05-03](https://user-images.githubusercontent.com/2988275/36171089-a14ab7ce-1101-11e8-8814-960f483eb5b8.png)

I hope you can help me!
Thanks!

**Comment by ctf0** [comment]
there is a couple of issues in ur `npm install` cmnd, like the cropperjs css and the extra spaces

try this
```
npm install vue vue-ls vue-tippy@v1 vue2-filters vue-bounty vue-notif vue-clipboard2 vue-awesome vue-touch@next axios dropzone cropperjs keycode babel-preset-es2015-node6 babel-preset-stage-2 --save
```

**Comment by eugeniregi** [comment]
Hello!
Sorry I must dismiss something in the previous image 
i use the command you provided 
and get this error
![captura de pantalla de 2018-02-14 17-54-15](https://user-images.githubusercontent.com/2988275/36216891-525ac802-11b0-11e8-82f1-5987a4d234ce.png)

Is there a way to know why is it fail?
Thanks!

**Comment by ctf0** [comment]
am not sure why u r getting this error, but `nyc` is a dep of https://github.com/gocanto/vuemit maybe u can ask there why u r getting this error.
