### ISSUE TITLE
Named Route not found (Laravel 5.6)

### ISSUE THREAD

**Issue by andreasbakir** [ctf0/Laravel-Media-Manager#33]
> What version of Laravel are you using? (nothing lower than v5.4).

5.6

> is it an issue related to installation or usage ?

Perhaps

> what is the error you are getting ?

After installing all the dependencies and publishing the config files. Going to the /media route will result in getting an error. The error says that: "Route [media.change_vis] not defined."

> Extra Info "attaching a screen shot would be very helpful"

<img width="1278" alt="schermafbeelding 2018-02-16 om 01 27 41" src="https://user-images.githubusercontent.com/7511536/36287970-a4d60818-12b8-11e8-9440-2fcfdcb002db.png">

**Comment by ctf0** [comment]
sorry for that, some how i missed updating the routes file, will push the fix asap
