### ISSUE TITLE
checkForRestrictedPath is not defined

### ISSUE THREAD

**Issue by Themesfa** [ctf0/Laravel-Media-Manager#34]
> What version of Laravel are you using? (nothing lower than v5.4).

5.5

> is it an issue related to installation or usage ?

installation 

> what is the error you are getting ?

checkForRestrictedPath is not defined

> Extra Info "attaching a screen shot would be very helpful"

![untitled](https://user-images.githubusercontent.com/20536674/36440352-cfa397de-1684-11e8-8b7c-bebd5b22d561.png)

**Comment by ctf0** [comment]
it seems i've missed that one, check https://github.com/ctf0/Laravel-Media-Manager/commit/71d24cf06408ca4b456ed6fdc1efc3ad2fedb032

this will be fixed in the next release.

**Comment by themesfa** [comment]
so when you publish next release ?

**Comment by Themesfa** [comment]
thank you ! it's working now ...
