### ISSUE TITLE
urls not supporting port

### ISSUE THREAD

**Issue by Themesfa** [ctf0/Laravel-Media-Manager#35]
> What version of Laravel are you using? (nothing lower than v5.4).

5.5

> is it an issue related to installation or usage ?

usage

laravel url : http://localhost:8000
the url of the images : http://localhost/storage/123456.png
but it must be http://localhost:8000/storage/123456.png
the port not added in images url .
how i can fix that ?

**Comment by ctf0** [comment]
try to test with `Storage::url('123456.png')` and see if it works or u still get the same error.

**Comment by Themesfa** [comment]
how i can fix that in media manager ?! images not loading in media manager panel ...
i think that you must fix that in your project .
![untitled](https://user-images.githubusercontent.com/20536674/36444662-2d475b4e-1691-11e8-8f4b-6b18329bb7bb.png)

**Comment by ctf0** [comment]
unless u test with the prev cmnd i provided, i cant help u

**Comment by eugeniregi** [comment]
Hello I get the same issue
It seems not work for the url...

![captura de pantalla de 2018-03-02 12-17-34](https://user-images.githubusercontent.com/2988275/36896787-3df0d6de-1e14-11e8-9dc4-722214862123.png)

In the app I have homestead.rest domain and in the url image appears  localhost...

Hope you can help !
Thanks!!

**Comment by Themesfa** [comment]
you can solve the problem by edit .env file .
change APP_URL option 
**FROM** : 
`APP_URL=http://localhost`
**TO** :
`APP_URL=http://localhost:8000`

then you should re run the serve command in terminal to apply changes.

**note:** in your case you must use yours used URL. not localhost:8000

**Comment by jasperf** [comment]
I had to change to `127.0.0.1:8000` do a `php artisan config:clear` and then `php artisan serve` again. That worked loading things properly.
