### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by thomasilmer** [ctf0/Laravel-Media-Manager#36]
> What version of Laravel are you using? (nothing lower than v5.4).

5.5

> is it an issue related to installation or usage ?

Usage

> what is the error you are getting ?

"Cannot assign to read only property 'exports' of object '#<Object>'"

> Extra Info "attaching a screen shot would be very helpful"

When going to the /media route I get this JavaScript error on a line with 'module.exports = new Vuemit()'
Might be related to https://github.com/webpack/webpack/issues/4039 ?

**Comment by ctf0** [comment]
have u tried this https://ctf0.wordpress.com/2017/09/12/laravel-mix-es6/ ?
