### ISSUE TITLE
I am a little confuse...

### ISSUE THREAD

**Issue by marcellopato** [ctf0/Laravel-Media-Manager#37]
How do I should install?
On an empty folder?
Git cloning?
On a Laravel folder?

Sorry to bother...

**Comment by ctf0** [comment]
> How do I should install?

1- install laravel https://laravel.com/docs/5.6#installing-laravel
2- navigate to the newly created project root
3- run `composer require ctf0/media-manager`

**Comment by marcellopato** [comment]
Well, thanks. It doesn't work at first!

**Comment by ctf0** [comment]
did u get a specific error on installation on the first time ?

**Comment by marcellopato** [comment]
Yes. But it was my fault. I've cloned the repo and ran the composer command also.
