### ISSUE TITLE
Demo Installation

### ISSUE THREAD

**Issue by 1mak** [ctf0/Laravel-Media-Manager#38]
Hi,

I was wondering if you have a demo installation of the media manager that you could show? It looks promising from the screenshot and the functions list as far as I can see. I'd just like to see it in action before I go further. :)

Thanks in advance and keep up the good work.

**Comment by ctf0** [comment]
i understand what u r after, but maybe u can tell me if u've tried to install it and what difficulties have u faced so i can ease/fix it ?

**Comment by tallcoder** [comment]
I'd appreciate that as well. I've been fighting with this all day so far and I cannot get it to work, even on it's own template/layout. Not to mention in the site I want this installed on.

**Comment by ctf0** [comment]
@tallcoder demo already added https://github.com/ctf0/Laravel-Media-Manager#usage
