### ISSUE TITLE
How to get a list of multi selected files?

### ISSUE THREAD

**Issue by 4KDA** [ctf0/Laravel-Media-Manager#40]
> What version of Laravel are you using? (nothing lower than v5.4).

5.5

> is it an issue related to installation or usage ?

No

> what is the error you are getting ?

No error.

If you select multiple files, the link will only link to the last one, but you need to get links to all the files. How?

**Comment by ctf0** [comment]
ah, actually no we dont have this option yet, as i thought that mostly ppl will need a link for individual not multi, still can u tell me what would be the case for such feature ?

**Comment by 4KDA** [comment]
we want to make a gallery in which you can leave a description of each picture, so the option of selecting a folder is not suitable, and choosing one file is long, because in the gallery can be a large number of pictures.

**Comment by 4KDA** [comment]
we want to make a gallery in which you can leave a description of each picture, so the option of selecting a folder is not suitable, and choosing one file is long, because in the gallery can be a large number of pictures.

**Comment by ctf0** [comment]
okay, i think i can add a new button that shows up on multi select and clicking on it will copy all the selected items links to the clipboard, is that what u r after ?

**Comment by 4KDA** [comment]
Yeah, that's what you need. Or simply correct the functionality of the "Bulk select" button, without adding new buttons, so that there is no confusion in similar buttons.

**Comment by 4KDA** [comment]
By the way (does not concern the current issue), "vue-awesome" has been updated to version 3.0 which does not have some icons used in your solution, which creates errors. Add a note to the description that you must install vue-awesome version 2.3.5 to avoid build errors.

**Comment by ctf0** [comment]
> Or simply correct the functionality of the "Bulk select" button, without adding new buttons, so that there is no confusion in similar buttons.

am not sure what u have in mind

**Comment by 4KDA** [comment]
Now, by clicking on the "bulk select" button, you can select many files to work with them inside the manager (move, delete), but it returns to the buffer only the last element link. Can I do so that in this case I return a list of all the selected ones, without adding additional buttons?

![image](https://user-images.githubusercontent.com/38465364/38933893-e821c766-4322-11e8-826d-581a7a1437e3.png)

**Comment by ctf0** [comment]
> but it returns to the buffer only the last element link

u mean the sidebar ? if yes, then i can add a little icon next to the **public url** to allow copying all the selected files links

if u mean that i auto-copy links to clipboard as you select new items, then no i prefer not doing so as this will ruin the user experience & will be an anti-pattern.

btw thanx for the **vue-awesome** headsup, i've updated the rdme

**Comment by 4KDA** [comment]
No. I mean the meaning that I can output to the input through vue. (as in your example [Use The Manager From A Modal](https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal)) 

Ok. You can make the "confirm select files" button, by click on which the value of clipboard will be updated to the links of the selected files (if one, then one link, if several, then all)?

**Comment by ctf0** [comment]
oh okay, i'll think of something for that later

**Comment by 4KDA** [comment]
Thank, we will wait)

**Comment by ctf0** [comment]
added, recheck wiki

**Comment by 4KDA** [comment]
Great! That's exactly what you need.
In Pull Request offered a small but important addition.
