### ISSUE TITLE
Get a relative path to the file

### ISSUE THREAD

**Issue by 4KDA** [ctf0/Laravel-Media-Manager#42]
> What version of Laravel are you using? (nothing lower than v5.4).

5.5

> is it an issue related to installation or usage ?

No

> what is the error you are getting ?

No error.

Thank you for adding the possibility of multi-selection, there is another request :-)

Please, add a config so that you can get a relative path to the file. I want to exclude the protocol and address of the site from the value. Yes, I can do this after getting the value from lmm, but it would be very cool if such an option was in lmm.

**Comment by ctf0** [comment]
i dont see an urge of adding such option, but u r welcome to make a PR
