### ISSUE TITLE
Undefined variable: cacheExp

### ISSUE THREAD

**Issue by matteo030** [ctf0/Laravel-Media-Manager#43]
I'm using Laravel 5.5, Media-Manager is installed and when i visit `http://127.0.0.1:8000/media` everything works. The problem is that when i load a view with the media-modal script in it, it gives me the error below 

<img width="1919" alt="schermata 202018-05-17 20alle 2010 25 59" src="https://user-images.githubusercontent.com/37375543/40168315-7973b4f2-59c3-11e8-99aa-0a37b7aa944f.png">

**Comment by ctf0** [comment]
yes, u r using a slightly old view file, plz check the latest release
https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/views/_manager.blade.php
 which have everything in place
