### ISSUE TITLE
Oh NO! Something Went Wrong

### ISSUE THREAD

**Issue by auzankyu** [ctf0/Laravel-Media-Manager#44]
> What version of Laravel are you using? (nothing lower than v5.4).

5.6

> is it an issue related to installation or usage ?

installation

> what is the error you are getting ?

Oh NO! Something Went Wrong

> Extra Info "attaching a screen shot would be very helpful"

![asdadasdsadadsadsadzzzzzzzzzzzzzzzzzz](https://user-images.githubusercontent.com/9339383/40572736-2a072184-60de-11e8-8ef6-f5280bab5e9a.PNG)

**Comment by ctf0** [comment]
plz expand the error object at the bottom and post its date

**Comment by auzankyu** [comment]
![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/9339383/40572842-c5c8e7b8-60e0-11e8-8220-6b5ad60e19c3.PNG)

**Comment by ctf0** [comment]
its related for not finding sqlite for the locked list to work, install sqlite and see if it fixes ur issue

**Comment by auzankyu** [comment]
but im using mySQL as database , so how?

**Comment by ctf0** [comment]
we use a separate db so the user if free to use whatever he wants for his main app.
