### ISSUE TITLE
Using with own Vue

### ISSUE THREAD

**Issue by dev-itbinc** [ctf0/Laravel-Media-Manager#45]
> What version of Laravel are you using? (nothing lower than v5.4).

5.6

> is it an issue related to installation or usage ?

no

> Extra Info "attaching a screen shot would be very helpful"

Can i use it with my Vue instance?

**Comment by ctf0** [comment]
yes of course, the one in the readme is just an example.

also edit the `resources/views/vendor/MediaManager/media.blade.php` with any changes u may need 👍 

basically u can edit anything u want, thats why the whole package resources are published together.

**Comment by dev-itbinc** [comment]
@ctf0 sorry, but i import _manager to my page and now have something like this 
![image](https://user-images.githubusercontent.com/35264291/41279112-3d4a99e8-6e34-11e8-905a-cc41576d0b32.png) (And cant understand why i have two messages about Vue dev tools)

**Comment by ctf0** [comment]
have u checked the wiki ? if yes, then

- disable laravel-debug
- tell me what exactly have u done
- show me the browser console

**Comment by dev-itbinc** [comment]
![image](https://user-images.githubusercontent.com/35264291/41279625-adcdc0e0-6e35-11e8-87a9-a30ee0ff8606.png)
its my console
![image](https://user-images.githubusercontent.com/35264291/41279633-b6b382d0-6e35-11e8-9df6-d1f166d834f7.png)
its my blade file

**Comment by ctf0** [comment]
okay, make sure to add both
```blade
@stack('styles')
@stack('scripts')
```

in ur main layout and see if it works

**Comment by ctf0** [comment]
ur main layout should mimic https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/views/media.blade.php

**Comment by dev-itbinc** [comment]
![image](https://user-images.githubusercontent.com/35264291/41279985-8c96347e-6e36-11e8-935d-2818d9c83178.png)
![image](https://user-images.githubusercontent.com/35264291/41279998-9200f07a-6e36-11e8-8edb-def0c0cdd26f.png)

**Comment by ctf0** [comment]
okay, ur `app/admin.js` should come after the `@stack('scripts')`, also clear the view cache and try again

**Comment by dev-itbinc** [comment]
![image](https://user-images.githubusercontent.com/35264291/41280622-0930aba8-6e38-11e8-8fa0-7368711534fd.png)
run php artisan view:clear. Same issue

**Comment by ctf0** [comment]
am not sure what exactly is ur issue, but i have almost the exact same setup as u.

can u make a repo ?

**Comment by dev-itbinc** [comment]
@ctf0 i can make gists from my webpack.min.js, view files and controller

**Comment by dev-itbinc** [comment]
https://gist.github.com/ebf65767fe24f53273c9e9d5787972bb

**Comment by dev-itbinc** [comment]
@ctf0 i found my issue. I forgot to make instance of Vue. But now i have other error. Cant find #app but i have it

**Comment by ctf0** [comment]
so all are good ?

**Comment by dev-itbinc** [comment]
@ctf0 i have found solution for my issue. maybe you have an example of modal? I want to understand how is it work

**Comment by ctf0** [comment]
> maybe you have an example of modal?

what u mean ?, btw if there is something that should be added to the readme to help others, do tell me

**Comment by dev-itbinc** [comment]
I want to understand how should work manager in modal. For example if i want use it with Article.

**Comment by ctf0** [comment]
the wiki is there for a reason https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal

**Comment by dev-itbinc** [comment]
@ctf0 i have seen wiki. I want to check it in browser and make sure that i did correct.

**Comment by ctf0** [comment]
u mean like send u a screen shot , am sorry am not sure what u mean !!!

**Comment by dev-itbinc** [comment]
i mean that want to know how it will be assigned with my entity from form?
