### ISSUE TITLE
Unknown Component in laravel 5.6 

### ISSUE THREAD

**Issue by naingyy** [ctf0/Laravel-Media-Manager#46]
> What version of Laravel are you using? (nothing lower than v5.4).

... Laravel 5.6

> is it an issue related to installation or usage ?

...installation

> what is the error you are getting ?

...unknown component

> Extra Info "attaching a screen shot would be very helpful"

...
![untitled](https://user-images.githubusercontent.com/8743514/41861280-cf851436-78c6-11e8-9be6-68fa6b9e1661.png)

**Comment by ctf0** [comment]
- make sure u have https://github.com/ctf0/Laravel-Media-Manager/blob/18025a371cef4a19f865dde6c59122c6611955c1/src/MediaManagerServiceProvider.php#L144-L146 under ur webpack.mix.js

- make sure u have initiated ur vue ex.
```
new Vue({
  'el': '#app'
})
```
and have changed the path https://github.com/ctf0/Laravel-Media-Manager/blob/18025a371cef4a19f865dde6c59122c6611955c1/src/resources/views/media.blade.php#L33

**Comment by yenyint** [comment]
Hi @ctf0 ,
Thanks for your reply.
I already make all that steps.npm is also compile well but its show that errors.Do I need to register components in app.js file?

**Comment by ctf0** [comment]
no, because `resources/assets/vendor/MediaManager/js/manager.js` already registers the comps globally.

can u dbl check the loaded js/css files in the browser ?

**Comment by yenyint** [comment]
Thanks @ctf0.

I will check .Do you have any other demo project installation refrence?Its would be better for all others newbie developers who want to use your package.
Thanks.

**Comment by yenyint** [comment]
Hi @ctf0,

I just create repo for unknown component error.
[Demo Project with laravel 5.6 ](https://github.com/nyeyint/laravel-media-manager-demo)

Everyting is already startup for your package.

**Comment by yenyint** [comment]
Ok. I get it.all laravel fresh installation already included configuration in app.js.I just comment these two line 

--------------------------------------------------

require('./bootstrap');

window.Vue = require('vue');

---------------------------------

**Comment by ctf0** [comment]
the only prob was having to init vue

> - make sure u have initiated ur vue ex.
> 
> new Vue({
>   'el': '#app'
> })

i will add a note about that to the rdme, anyway ur problem is solved now ?

**Comment by ctf0** [comment]
rdme updated https://github.com/ctf0/Laravel-Media-Manager/blob/master/README.md

**Comment by yenyint** [comment]
@ctf0 

Yeah my problem is solved now.Thanks.

**Comment by yenyint** [comment]
I think your readme update is not perfact.I think error is bez of this line.

`window.Vue = require('vue');`

u can check in my demo [repo.](https://github.com/nyeyint/laravel-media-manager-demo/blob/master/resources/assets/js/app.js)

**Comment by ctf0** [comment]
i dont think so, anyway i've removed this line from the `manager.js` file so we now rely on the user `app.js` file

**Comment by yenyint** [comment]
that great.Thanks for your discussion.
