### ISSUE TITLE
Use Mysql Database instead Sqlite

### ISSUE THREAD

**Issue by MonrealRyan** [ctf0/Laravel-Media-Manager#47]
> What version of Laravel are you using? (nothing lower than v5.4).

5.6.*

I was wondering if this package can use MySQL instead it's default database SQLite. I can't find how can I do it. thanks for the help

**Comment by ctf0** [comment]
the reason we use sqlite is 
- small
- light
- doesnt enforce a db choice on the user "mysql, PostgreSQL, mongo, etc.."
- dont need any long lived resources "cpu, ram", its more like a text file

as for how to change it, check [updated wiki](https://github.com/ctf0/Laravel-Media-Manager/wiki/Lock-Files-&-Folder)

**Comment by MonrealRyan** [comment]
Thank you :)
