### ISSUE TITLE
Undefined variable: base_url when I go to mydomain/media

### ISSUE THREAD

**Issue by trungdung1995** [ctf0/Laravel-Media-Manager#48]
> What version of Laravel are you using? (nothing lower than v5.4).

I installed laravel 5.6

> is it an issue related to installation or usage ?

...

> what is the error you are getting ?

Undefined variable: base_url

> Extra Info "attaching a screen shot would be very helpful"

![screen shot 2018-07-23 at 20 53 52](https://user-images.githubusercontent.com/33725783/43080731-9b6be30a-8eba-11e8-8cc8-852ef8737ffe.png)

**Comment by ctf0** [comment]
clear the view cache and try again, however if u've tried the demo and it worked then its probably related to ur setup.

**Comment by tallcoder** [comment]
I'm having the same problem. New install ... no ideas? Not sure I would call it invalid, it's happening to someone else. I've tried deleting view cache, but no luck.

**Comment by ctf0** [comment]
@tallcoder & @trungdung1995 have u ran any of `npm watch/dev/prod` ?

have u followed the installation steps https://github.com/ctf0/Laravel-Media-Manager#installation ?

**Comment by tongvanduc** [comment]
I have the same problem
It does not handle the problem
When I used demo n worked,
However, when I add the interface, a white screen
This is a bug fix

**Comment by ctf0** [comment]
@tongvanduc the variable gets registered based on a condition

https://github.com/ctf0/Laravel-Media-Manager/blob/cb4b72f712a45b79c473431fd53a5a230deba2db/src/MediaManagerServiceProvider.php#L21-L23

so if that folder doesnt exist, u will get the error, so you have to compile the assets b4 u start using the manager.

**Comment by tongvanduc** [comment]
Thanks for the answer
I done
