### ISSUE TITLE
How to include laravel media manager in bootstrap admin template?

### ISSUE THREAD

**Issue by trungdung1995** [ctf0/Laravel-Media-Manager#50]
I see a conflict css. How to fix that?
![screen shot 2018-07-24 at 21 46 24](https://user-images.githubusercontent.com/33725783/43146253-0ca78f26-8f8b-11e8-876d-07f17e833f4e.png)

**Comment by ctf0** [comment]
@trungdung1995 stop opening unrelated tickets or u will be blocked.

if u opened https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/views/media.blade.php#L11 clearly we use bulma, so using other/custom css is up to you to fiddle with.
