### ISSUE TITLE
[Helps] I do not understand why this error occurred while some days before I used it, it still works normally

### ISSUE THREAD

**Issue by tongvanduc** [ctf0/Laravel-Media-Manager#51]
![image](https://user-images.githubusercontent.com/18494990/43676740-364786da-9821-11e8-95fd-0dd07af85722.png)

**Comment by ctf0** [comment]
first there is a template for issues, plz use it.

second i cant see what exactly is the error other than `token mismatch` which is not exactly helpful, so 
- disable laravel-debugbar
- try to clear the browser cache,cookies
- flush laravel session
- check the errors in console

**Comment by tongvanduc** [comment]
Thank you!
