### ISSUE TITLE
Can't install Package, getting errors!

### ISSUE THREAD

**Issue by vubavuba** [ctf0/Laravel-Media-Manager#53]
> What version of Laravel are you using? (nothing lower than v5.4).

Laravel Version 5.5

> is it an issue related to installation or usage ?

Installation Problem in Composer

> what is the error you are getting ?

  Problem 1
    - Installation request for ctf0/media-manager ^3.2 -> satisfiable by ctf0/media-manager[v3.2.0].
    - ctf0/media-manager v3.2.0 requires maennchen/zipstream-php ~1.0 -> satisfiable by maennchen/zipstream-php[v1.0.0-alpha.1] but these conflict with your requirements or minimum-stability.

Seems to be any conflict with external packages. Would like to use this package. Maybe anyone can help me here.

Thanks!

**Comment by ctf0** [comment]
because laravel v5.5 use php v7
and maennchen/zipstream-php use php v7.1

so you need to update ur php which is recommended

**Comment by vubavuba** [comment]
OK thanks a lot, I give it a try when I am back in office. Will reply if it helped.

**Comment by vubavuba** [comment]
Today I updated my php version, now I have version 7.2.8 but I still get the same error.

EDIT: Seems to be a problem with Laravel 5.5 Version. On a new Version of 5.6, I have no problem to install it. But I want to run on of 5.5, as it is the LTS Version. Still anyone an idea?

**Comment by avlads** [comment]
Add minimum-stability and prefer-stable to your composer.json

    "minimum-stability": "dev",
    "prefer-stable": true

**Comment by vubavuba** [comment]
OK I will check it again. Switched now to 5.6 and it worked.

**Comment by ctf0** [comment]
@vubavuba u better stay as up to date as possible because LTS doesnt get bug fixes, only security updates

**Comment by kfulk14** [comment]
@ctf0 from what I have read LTS does get bug fixes  https://laravel-news.com/laravel-release-process
