### ISSUE TITLE
Demo: Plyr install

### ISSUE THREAD

**Issue by salierg** [ctf0/Laravel-Media-Manager#55]
> What version of Laravel are you using? (nothing lower than v5.4).

I used the demo

> is it an issue related to installation or usage ?

Issue when running npm run watch to compile assets

> what is the error you are getting ?

Plyr is missing

> Extra Info "attaching a screen shot would be very helpful"

> Solution:

npm install plyr
THEN
npm run watch (or npm run production)

**Comment by ctf0** [comment]
ah yes, i forgot to update the demo npm packages list, thanx for the headsup
