### ISSUE TITLE
need to upload mp4 or audio or video files

### ISSUE THREAD

**Issue by saifuldhaka** [ctf0/Laravel-Media-Manager#56]
hi i am using laravel 5.5 
i want to upload video files (mp4/mp3) like is image.
have any solution please?

**Comment by ctf0** [comment]
am not sure what u mean but yes u surly can upload any file type you want

**Comment by saifuldhaka** [comment]
@ctf0 hi, in my project i can upload image and same them in database / server directory. 
now i want to to upload video files.
i am looking a solution to upload mp4 files.

**Comment by ctf0** [comment]
i dont understand what exactly u r after so am sorry i cant help u
