### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by KeanuJanssen** [ctf0/Laravel-Media-Manager#57]
> What version of Laravel are you using? (nothing lower than v5.4).

v5.6

> is it an issue related to installation or usage ?

no

> what is the error you are getting ?

no error, the package is not very responsive. When translated or a smaller screen the buttons will get out of line

> Extra Info "attaching a screen shot would be very helpful"

![image](https://user-images.githubusercontent.com/38426534/45697323-d7b73800-bb65-11e8-91dd-a23ed1cd6599.png)
![image](https://user-images.githubusercontent.com/38426534/45697351-eaca0800-bb65-11e8-87e3-b8f72f65d270.png)
![image](https://user-images.githubusercontent.com/38426534/45697392-046b4f80-bb66-11e8-9268-e31330c6086a.png)

> Do You Know A Solution For this Issue ?

Check on responsiveness, try to put longer strings in the translation and test when screen is smaller.

Looking forward to see the difference.

Kind regards,

**Comment by ctf0** [comment]
this is totally handled by bulma

**Comment by ctf0** [comment]
i will close this for now as its kinda out of the package scope, if u can fix it and send a PR that would awesome.
