### ISSUE TITLE
Demo installation failing

### ISSUE THREAD

**Issue by LarryBarker** [ctf0/Laravel-Media-Manager#58]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7

> is it an issue related to installation or usage ?

Yes.

> what is the error you are getting ?
```
ERROR in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/lib/loader.js??ref--6-5!./resources/assets/vendor/MediaManager/sass/media.scss
Module build failed:
undefined
                     ^
      Undefined variable: "$progress-bars".
      in C:\Users\lbarker\Code\laravel-media-manager-demo\resources\assets\vendor\MediaManager\sass\packages\progress.scss (line 33, column 23)
 @ ./resources/assets/vendor/MediaManager/sass/media.scss 4:14-292
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/vendor/MediaManager/sass/media.scss
```

> Extra Info "attaching a screen shot would be very helpful"

> Do You Know A Solution For this Issue ?

I've tried following all the suggestions here and on other repo's [https://github.com/nyeyint/laravel-media-manager-demo](https://github.com/nyeyint/laravel-media-manager-demo) but neither seem to be working.

**Comment by ctf0** [comment]
actually the `MediaManager/sass/media.scss` no longer exist, it was changed along with many other updates, have u ran 
```
php artisan vendor:publish --provider="ctf0\MediaManager\MediaManagerServiceProvider" --force
``` 
?

**Comment by LarryBarker** [comment]
Yes, I followed all of the steps on the demo install section.

**Comment by ctf0** [comment]
this is weird, check the `vendor/ctf0/media-manager/logs` folder and tell me which version u have **it should be `v3.2.7`**

**Comment by LarryBarker** [comment]
Ok, I’m going to rebuild the demo app and let you know what happens.

**Comment by LarryBarker** [comment]
Well, I apologize for the mixup here. After a fresh install of the Demo app, I was able to run `npm run watch` and serve up with artisan, no problems. I think I may have gotten a couple of the install steps out of order my first run.

Thanks for your time and quick response!

**Comment by ctf0** [comment]
np :+1:
