### ISSUE TITLE
 Fix sortBy:size To Work Properly With (kb vs Mb).

### ISSUE THREAD

**Issue by chriys** [ctf0/Laravel-Media-Manager#6]
Can you please give more explanation to this issue?

**Comment by ctf0** [comment]
atm the filter we use to sort the items by size doesnt understand the `kb vs Mb` and it only looks at numbers, ex
```js
[
{file 1: '980kb'},
{file 2: '7 Mb'},
{file 3: '500kb'}, 
'etc...'
]
```

https://github.com/freearhey/vue2-filters/issues/20

**Comment by chriys** [comment]
Ok I get it. I'm looking their code souce. Could you please specify where you're calling the filter orderBy inside script.js ?

**Comment by ctf0** [comment]
its used in the view file as its a part of the vue2-filters package https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/views/bulma/media.blade.php#L242

**Comment by chriys** [comment]
do you mind if we tweak their functionality to suit our needs ?

**Comment by ctf0** [comment]
plz, go for it. :+1:

**Comment by ctf0** [comment]
check next release
