### ISSUE TITLE
Config media folder

### ISSUE THREAD

**Issue by itbk95** [ctf0/Laravel-Media-Manager#60]
Can you help me config folder media file to load all files, when I try install laravel media manager via [Demo](https://github.com/ctf0/demos/tree/media-manager), its not point to http://localhost/project_name/public/storage...
I want to point to folder such as: public/media (option is not in config/mediaManager.php), how can I do that?

**Comment by ctf0** [comment]
the manager depend on your filesystem disks,  https://laravel.com/docs/5.7/filesystem#introduction
