### ISSUE TITLE
Can not select folder or fullscreen mode

### ISSUE THREAD

**Issue by tantana5** [ctf0/Laravel-Media-Manager#61]
When i click a folder to explore them or click full screen mode button, i got an error in console:
```
media.js:3318 [Vue warn]: Error in event handler for "dbltap": "ReferenceError: type is not defined"

found in

---> <VTouch>... (1 recursive calls)
       <MediaManager> at resources/assets/vendor/MediaManager/js/components/manager.vue
         <Root>

**Error here:**
if (type == 'hold') {
                this.setSelected(file, i);
                this.imageEditor();

                // anything but images, toggle lock
                if (!this.selectedFileIs('image')) {
                    this.lockFileForm();
                }
            }
```

**Comment by ctf0** [comment]
its fixed in the latest release, plz update

**Comment by olipiskandar** [comment]
hallo...
i got error like above issue..
![download](https://user-images.githubusercontent.com/4706142/46683068-74c33900-cc19-11e8-8b89-da1c66127748.png)

**Comment by ctf0** [comment]
@olipiskandar plz update the resources files 
```
php artisan vendor:publish --provider="ctf0\MediaManager\MediaManagerServiceProvider" --force
```

**Comment by olipiskandar** [comment]
> @olipiskandar plz update the resources files
> 
> ```
> php artisan vendor:publish --provider="ctf0\MediaManager\MediaManagerServiceProvider" --force
> ```

still not work..
after clear chace still not work

**Comment by ctf0** [comment]
the error in the ur ss console is related to this line
https://github.com/ctf0/Laravel-Media-Manager/blob/74015059e042584175adb456ca7127fbd13ab7cf/src/resources/assets/js/modules/gestures.js#L137

which is solved, however u can make a repo with ur setup so i can investigate the problem more

**Comment by olipiskandar** [comment]
> the error in the ur ss console is related to this line
> [Laravel-Media-Manager/src/resources/assets/js/modules/gestures.js](https://github.com/ctf0/Laravel-Media-Manager/blob/74015059e042584175adb456ca7127fbd13ab7cf/src/resources/assets/js/modules/gestures.js#L137)
> 
> Line 137 in [7401505](/ctf0/Laravel-Media-Manager/commit/74015059e042584175adb456ca7127fbd13ab7cf)
> 
>  switch (type) { 
> which is solved, however u can make a repo with ur setup so i can investigate the problem more

its work..
after create new project & use yarn
