### ISSUE TITLE
Composer dependencies issues on installation

### ISSUE THREAD

**Issue by Naxon** [ctf0/Laravel-Media-Manager#62]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7.8

> is it an issue related to installation or usage ?

installation

> what is the error you are getting ?

Composer dependencies issues (screenshot attached).

> Extra Info "attaching a screen shot would be very helpful"

https://imgur.com/BTm8ool

**Comment by ctf0** [comment]
this is related to `maennchen/zipstream-php` apparently there is another package in ur setup is using an old version which has a conflict with the one that comes with mm which is out of my scope.

still to fix ur issue you need to remove the older version.
