### ISSUE TITLE
npm run watch error.

### ISSUE THREAD

**Issue by georgetulev** [ctf0/Laravel-Media-Manager#64]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7.8

> is it an issue related to installation or usage ?

Installation

> what is the error you are getting ?

Running: npm run watch 

Then I get the following error
```
ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve '../vendor/MediaManager/js/manager' in '/var/www/html/resources/js'
 @ ./resources/js/app.js 12:0-44
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/assets/vendor/MediaManager/sass/manager.scss
```

> Extra Info "attaching a screen shot would be very helpful"

...

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
am not sure how the vendor folder path is relative to ur js folder, so instead of `../vendor/MediaManager/js/manager` try to add the correct path according to ur `app.js` file

**Comment by georgetulev** [comment]
Solved it by changing the path to:

require('./../assets/vendor/MediaManager/js/manager.js');

Thanks for your fast reply!

**Comment by ctf0** [comment]
rdme updated
