### ISSUE TITLE
Property or method "orderBy" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by mckayze** [ctf0/Laravel-Media-Manager#65]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7.15

> is it an issue related to installation or usage ?

Usage

> what is the error you are getting ?

Basically when ive installed everything and successfully compiled using "npm run watch", i navigate to /media on my website, and i get the following error.

I've put it here cause its quite long, basically sais this:
"Property or method "orderBy" is not defined on the instance but referenced during render."

> Extra Info "attaching a screen shot would be very helpful"

Full error can be found here: http://codepad.org/QHjZgEQp

> Do You Know A Solution For this Issue ?

No idea, not the most gifted with vue.js

**Comment by ctf0** [comment]
the only place where `orderBy` is used is at https://github.com/ctf0/Laravel-Media-Manager/search?q=orderBy&unscoped_q=orderBy

which is a part of [vue2-filters](https://github.com/freearhey/vue2-filters), but apparently after a recent update of the package the filters needs to be manually registered, so update ur installed `manager.vue` [with this](https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/assets/js/components/manager.vue) and try again

**Comment by mckayze** [comment]
@ctf0 This is a confirmed fix, thank you for the quick reply!
