### ISSUE TITLE
Use the Manager from a Modal

### ISSUE THREAD

**Issue by BechirAhmed** [ctf0/Laravel-Media-Manager#67]
> What version of Laravel are you using? (nothing lower than v5.4).

I use Laravel v5.7

> is it an issue related to installation or usage ?

Usage from modal

> what is the error you are getting ?

I use The Manager from a modal to update or set my app logo, by following this example [Use The Manager From A Modal](https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal), but it's not working.

> Extra Info "attaching a screen shot would be very helpful"

Maybe i didn't understand the example or the way to use the manager from a modal.
If there a real example well explained please provide it.
Thanks!

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
can u make a repo with ur current progress ?

**Comment by BechirAhmed** [comment]
> can u make a repo with ur current progress ?

@ctf0  I've already have a project on github with the manager implemented, [repo](https://github.com/RimAcademy/RimAcademy)

**Comment by ctf0** [comment]
i will check it and get back to u

**Comment by BechirAhmed** [comment]
> i will check it and get back to u

Thanks so much

**Comment by ctf0** [comment]
sorry for the delay, i've checked the code and i believe u were using the [old wiki](https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal/ebf46660740accc7f9de0bd6454d07768f769f1d) 👎 

plz check the [new one ](https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal) 🏆 and update ur [view](https://github.com/RimAcademy/RimAcademy/blob/master/resources/views/ra-admin/settings/edit.blade.php#L19-L42) accordingly 💯

**Comment by BechirAhmed** [comment]
Thanks @ctf0  for your time, but I use the last one [new one](https://github.com/ctf0/Laravel-Media-Manager/wiki/Use-The-Manager-From-A-Modal), and my [view ](https://github.com/RimAcademy/RimAcademy/blob/master/resources/views/ra-admin/settings/edit.blade.php#L19-L42 )it's the same as the wiki, So please if you can made those changes u meant for me I'll appreciate that, cuz i've tried every solution i can imagine.
And if u want any explanation of my code i can provide it to you.

**Comment by BechirAhmed** [comment]
I didn't understand this part of code
```
{{-- items selector --}}
<media-modal old="{{ old('logo', asset('storage/'.AppSettings::get('logo', 'default value'))) }}" item="logo" :name="inputName"></media-modal>

<form action="" method="" role="form">

   {{-- logo --}}
   <section>
     <img :src="logo">
     <input type="hidden" name="logo" :value="logo"/>
     <button @click="toggleModalFor('logo')">Upload logo</button>
   </section>
</form>
```
Cuz when ever i clicked on that button(Upload logo), the form submitted and refresh the page, and the url of the <media-modal> passed to url, but i don't have a choice to select the picture for first!

**Comment by ctf0** [comment]
> but I use the last one new one, and my view it's the same as the wiki, 

u r right, i was confused between the `media-manager-modal` & `media-modal`, sorry for that.

> Cuz when ever i clicked on that button(Upload logo), the form submitted and refresh the page, and the url of the passed to url, but i don't have a choice to select the picture for first!

the reason its not working as expected is that button inside forms have the default type of submit, so u can add `type="button"` to the upload logo button or use any other tag ex.
```html
<div @click="toggleModalFor('logo')">Upload logo</div>
```

**Comment by BechirAhmed** [comment]
Thanks so much for your time, it works like a charm
