### ISSUE TITLE
Media Modal: Thumbnail not loading

### ISSUE THREAD

**Issue by thanhtung2693** [ctf0/Laravel-Media-Manager#68]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7

> is it an issue related to installation or usage ?

Usage

> what is the error you are getting ?

Hi, I'm using TinyMCE, when the media modal is opened, the thumbnal in the "__box-img" is not loaded (no img tag) unless I do something with the window (resize, open developer tool...). I've set the lazy_load_image_on_click to false but still not working.

> Extra Info "attaching a screen shot would be very helpful"

![image](https://user-images.githubusercontent.com/4317955/50386319-da05d100-0716-11e9-8916-d3f3f4e3a7df.png)

> Do You Know A Solution For this Issue ?

Temporarily, I have to go to lazyLoading/normal.vue and set the this.intersected = true (comment the this.obrserver()).

**Comment by ctf0** [comment]
this is an issue with the intersectionObserver(), so for a start can u check if the console has an error.

**Comment by thanhtung2693** [comment]
Hi, unfortunately the console has no error :(. I've uploaded some images and only few images are loaded

![image](https://user-images.githubusercontent.com/4317955/50390402-6e008880-0769-11e9-92fd-e9774f4cc757.png)

**Comment by ctf0** [comment]
does this happens with all the browsers or only one ?

**Comment by thanhtung2693** [comment]
Happens with Chrome, Safari, Edge, Firefox and maybe all :(

**Comment by ctf0** [comment]
@thanhtung2693 sorry for the delay, if the issue still persist, can u make a demo repo so i can test with ?
