### ISSUE TITLE
Blank page after install and JS error: mix is not defined

### ISSUE THREAD

**Issue by folkevil** [ctf0/Laravel-Media-Manager#69]
> What version of Laravel are you using? (nothing lower than v5.4).

Laravel 5.7

> is it an issue related to installation or usage ?

Blank page while open /media

> what is the error you are getting ?

```
app.js:47756 Uncaught ReferenceError: mix is not defined
    at Object../resources/assets/js/app.js (app.js:47756)
    at __webpack_require__ (app.js:20)
    at Object.0 (app.js:47868)
    at __webpack_require__ (app.js:20)
    at app.js:84
    at app.js:87
```

> Extra Info "attaching a screen shot would be very helpful"

My app.js content

```
require('./bootstrap');
//require('../assets/vendor/MediaManager/js/manager')
require('../vendor/MediaManager/js/components/manager');
window.Vue = require('vue');
const app = new Vue({
    el: '#app'
});
```

**Comment by ctf0** [comment]
the `window.Vue = require('vue');` should be declared **b4** `require('../vendor/MediaManager/js/components/manager');` , 

am not sure is this will solve ur issue or not but plz try and reply back
