### ISSUE TITLE
There are no commands defined in the "mm" namespace.

### ISSUE THREAD

**Issue by chriys** [ctf0/Laravel-Media-Manager#7]
In Laravel 5.4.32 running the command `php artisan mm:append` returns error message and performs no operation. Beside the fact that it doesn't appear in the list of artisan commands.

**Comment by ctf0** [comment]
which version of the package r u using ? make sure its v1.0.5 or above

**Comment by chriys** [comment]
@ctf0 I'm using v1.0.6

**Comment by ctf0** [comment]
uninstall and reinstall the package again
