### ISSUE TITLE
app.js  [Vue warn]: Error compiling template:

### ISSUE THREAD

**Issue by kfulk14** [ctf0/Laravel-Media-Manager#70]
Receving error when visiting /media

"ctf0/media-manager": "^3.3",
"vue-notif": "^1.1.10"

**Comment by ctf0** [comment]
the issue ticket have a template, plz use it ex.

> What version of Laravel are you using? (nothing lower than v5.4).

...

> is it an issue related to installation or usage ?

...

> what is the error you are getting ?

...

> Extra Info "attaching a screen shot would be very helpful"

...

> Do You Know A Solution For this Issue ?

...
