### ISSUE TITLE
[Vue warn]: Error compiling template

### ISSUE THREAD

**Issue by lukasirsak** [ctf0/Laravel-Media-Manager#71]
> What version of Laravel are you using? (nothing lower than v5.4).
5.7.19

> is it an issue related to installation or usage ?
Installation

> what is the error you are getting ?
In browser console (5 errors):

First one:
```
[Vue warn]: Error compiling template:

<section id="app" v-cloak="">
        
        <div class="notif-container">
            <my-notification></my-notification>
        </div>

        <div class="container is-fluid">
            <div class="columns">
                
                <div class="column">
                    <media-manager inline-template="" v-cloak="" :config="{&quot;baseUrl&quot;:&quot;http:\/\/intranet.loc\/storage\/&quot;,&quot;hideFilesExt&quot;:true,&quot;lazyLoad&quot;:false,&quot;mimeTypes&quot;:{&quot;image&quot;:[&quot;binary\/octet-stream&quot;],&quot;archive&quot;:[&quot;application\/x-tar&quot;,&quot;application\/zip&quot;]},&quot;cacheExp&quot;:60,&quot;broadcasting&quot;:false,&quot;gfi&quot;:true,&quot;ratioBar&quot;:true}" :routes="{&quot;files&quot;:&quot;http:\/\/intranet.loc\/media\/files&quot;,&quot;dirs&quot;:&quot;http:\/\/intranet.loc\/media\/directories&quot;,&quot;lock&quot;:&quot;http:\/\/intranet.loc\/media\/lock-file&quot;,&quot;visibility&quot;:&quot;http:\/\/intranet.loc\/media\/change-vis&quot;,&quot;upload&quot;:&quot;http:\/\/intranet.loc\/media\/upload&quot;}" :translations="{&quot;copied&quot;:&quot;Copied&quot;,&quot;copy_success&quot;:&quot;Successfully Copied&quot;,&quot;create_folder_notif&quot;:&quot;New Folder Was created&quot;,&quot;create_success&quot;:&quot;Successfully Created&quot;,&quot;delete_success&quot;:&quot;Successfully Deleted&quot;,&quot;downloaded&quot;:&quot;Downloaded&quot;,&quot;error_altered_fwli&quot;:&quot;Can't Be Moved, Renamed Or Deleted Because It Has Some Locked Items&quot;,&quot;find&quot;:&quot;Find...&quot;,&quot;found&quot;:&quot;Found&quot;,&quot;glbl_search&quot;:&quot;Global Search&quot;,&quot;glbl_search_avail&quot;:&quot;Global Search Is Now Available.&quot;,&quot;go_to_folder&quot;:&quot;Go To Folder !&quot;,&quot;move_success&quot;:&quot;Successfully Moved&quot;,&quot;new_uploads_notif&quot;:&quot;New Items Were Uploaded&quot;,&quot;no_val&quot;:&quot;Maybe You Should Add Something First !!!&quot;,&quot;nothing_found&quot;:&quot;Nothing Found&quot;,&quot;refresh_notif&quot;:&quot;Press The Refresh Button To View Them&quot;,&quot;rename_success&quot;:&quot;Successfully Renamed&quot;,&quot;save_success&quot;:&quot;Successfully Saved As&quot;,&quot;sep_download&quot;:&quot;Folders Should Be Downloaded Separately&quot;,&quot;stand_by&quot;:&quot;Please Stand By ...&quot;,&quot;to_cp&quot;:&quot;Copy Link To Clipboard&quot;,&quot;upload_success&quot;:&quot;Successfully Uploaded&quot;}" :in-modal="false" :hide-ext="[]" :hide-path="[]" :restrict="{}" :user-id="0" :upload-panel-img-list="[&quot;\/assets\/vendor\/MediaManager\/patterns\/gif\/5b98026bab87a.gif&quot;,&quot;\/assets\/vendor\/MediaManager\/patterns\/still\/nyc-candy.png&quot;]">

    <div class="">


```

> Extra Info "attaching a screen shot would be very helpful"

![snimka obrazovky 2019-01-07 o 13 37 40](https://user-images.githubusercontent.com/30669262/50768649-75ec1c80-1281-11e9-9428-f7f1c99d8077.png)
![snimka obrazovky 2019-01-07 o 13 37 47](https://user-images.githubusercontent.com/30669262/50768656-78e70d00-1281-11e9-8144-8f822689eaf5.png)

Installed using `laravel new project` command, following [installation guide](https://github.com/ctf0/Laravel-Media-Manager#installation)

node v10.12.0
yarn 1.10.1

`Npm run watch` goes green (DONE). After visiting /media page js blows up (errors in screenshots).

Tried on multiple browsers same result. You should be able to confirm this behaviour running `laravel new whatever` cmd. and implementing package as mentioned in installation guide. 

Thank you. 

Wondering maybe this problem can be related to new laravel-mix version and webpack 4. [laravel mix](https://www.npmjs.com/package/laravel-mix)

**Comment by ctf0** [comment]
this is definitely related to the new laravel-mix v4, still will 2xcheck to make sure

ref: https://laravel-mix.com/docs/4.0/upgrade#notes

**Comment by manuweg** [comment]
Same problem. Any workaround suggestion?

**Comment by ctf0** [comment]
sorry for the long delay but am super busy with my day job, will try to get this fixed as soon as possible

**Comment by doitonlinemedia** [comment]
**Edit**

Found a workaround.
Install version 3 of laravel-mix.

`npm remove laravel-mix`

`npm install laravel-mix@3.0.0`

**Comment by charitablehumans** [comment]
Any estimate on when this will be fixed to work laravel-mix 4?

**Comment by ctf0** [comment]
i've made some changes according to the l-m upgrade notes but i couldn't test it yet as my mac just died on me, 

so can anyone try with the updated [demo copy](https://github.com/ctf0/Laravel-Media-Manager) and reply back with their findings ?

**Comment by charitablehumans** [comment]
> i've made some changes according to the l-m upgrade notes but i couldn't test it yet as my mac just died on me,
> 
> so can anyone try with the updated [demo copy](https://github.com/ctf0/Laravel-Media-Manager) and reply back with their findings ?

It's not working for me, but I'm not sure if I downloaded the demo version or not, I just followed the instructions listed on the page you linked to, installing through composer.

**Comment by ctf0** [comment]
@charitablehumans my bad, i linked the wrong repo, here is the [correct one](https://github.com/ctf0/demos/tree/media-manager)
