### ISSUE TITLE
Placing #anything behind url will ignore the stricted folder and show root.

### ISSUE THREAD

**Issue by doitonlinemedia** [ctf0/Laravel-Media-Manager#72]
> What version of Laravel are you using? (nothing lower than v5.4).

**Laravel 5.7**

> is it an issue related to installation or usage ?

**Usage**

> what is the error you are getting ?

No error, but manager is showing the files from the root folder if hashtag is in url, while restricted folder is set.
Reloading the page fixes it for that url.
Renewing the url with #somethingdifferent bugs again until refresh

> Do You Know A Solution For this Issue ?

Nope :(

**Comment by ctf0** [comment]
the way it happens right now is we get the url and split it into segments so we compare them against the restricted paths, i can check for some special chars and remove them from those segments but that means that i will also have to restrict them from folders names when the user create/rename folders.

**Comment by ctf0** [comment]
@doitonlinemedia i've updated the url path check to remove the hashbang `#` from it, plz update ur copy with [url.js](https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/assets/js/modules/url.js) and recheck if it solves the issue
