### ISSUE TITLE
Undefined variable: patterns

### ISSUE THREAD

**Issue by bocanhcam** [ctf0/Laravel-Media-Manager#74]
Undefined variable: patterns (View: ../resources/views/vendor/MediaManager/_manager.blade.php)

I have this issue after doing everything. I was trying to use the demo and it has the same issue.

Laravel 5.7

**Comment by ctf0** [comment]
please make sure that u have published the assets first, also check https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/MediaManagerServiceProvider.php incase you have changes any of the paths the manager use to operate

**Comment by bocanhcam** [comment]
You mean this line right
`php artisan vendor:publish --provider="ctf0\MediaManager\MediaManagerServiceProvider"
`
I did it. I did everything in the docs and nothing goes wrong. And I haven't changed any directory.

**Comment by ctf0** [comment]
can u make a repo so i can test with ?

**Comment by ctf0** [comment]
plz update to the latest release
