### ISSUE TITLE
have trouble with npm run watch and blan page in /media route

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [ctf0/Laravel-Media-Manager#76]
hi my config is write and i am sure that i install all the js package and this is my app.js file
require('./bootstrap');
window.Vue = require('vue');
//require('../assets/vendor/MediaManager/js/manager')
require('../assets/vendor/MediaManager/js/components/manager');
const app = new Vue({
    el: '#app'
});
and yet when i run npm  run watch it stuck at

(3128:3) start value has mixed support, consider using flex-start instead
 @ ./resources/assets/vendor/MediaManager/sass/manager.scss 2:14-294
and when i open /media i got a blank page

**Comment by ctf0** [comment]
first, plz use the ticket template, its there for a reason
second, check your console for the errors and post them here so i can help u
third, properly format ur ticket using markdown so **i** or **anyone else** can understand what u r facing
