### ISSUE TITLE
blank page and npm run watch error

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [ctf0/Laravel-Media-Manager#77]
> What version of Laravel are you using? (nothing lower than v5.4).

laravel 5.7

> is it an issue related to installation or usage ?

i think both

> what is the error you are getting ?

when in last step of installation i run npm run watch i got below error and when i try the /media route it load blank page

> Extra Info "attaching a screen shot would be very helpful"

when i run npm run watch i got this and run /media will return blank page

```
WARNING in ./resources/assets/vendor/MediaManager/sass/manager.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss!./node_modul
es/resolve-url-loader??ref--6-4!./node_modules/sass-loader/lib/loader.js??ref--6-5!./resources/assets/vendor/MediaManager/sass/manager.scss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(3128:3) start value has mixed support, consider using flex-start instead
 @ ./resources/assets/vendor/MediaManager/sass/manager.scss 2:14-294

WARNING in ./resources/assets/vendor/MediaManager/sass/manager.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss!./node_modul
es/resolve-url-loader??ref--6-4!./node_modules/sass-loader/lib/loader.js??ref--6-5!./resources/assets/vendor/MediaManager/sass/manager.scss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(3128:3) start value has mixed support, consider using flex-start instead
 @ ./resources/assets/vendor/MediaManager/sass/manager.scss 2:14-294
```

> Do You Know A Solution For this Issue ?

not yet

**Comment by ctf0** [comment]
from the error, the problem seems to be with [this line](https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/assets/sass/manager.scss#L294) which is weird, so try to change it to `flex-start` as the error says and try again, 

also try to check the browser console in case there is an issue with vue.
