### ISSUE TITLE
data: {…}, status: 500, statusText: "",

### ISSUE THREAD

**Issue by masumonline** [ctf0/Laravel-Media-Manager#78]
> What version of Laravel are you using? (nothing lower than v5.4).
v5.7
...

> is it an issue related to installation or usage ?
usage.
...

> what is the error you are getting ?
Oh NO! Something Went Wrong. when i check the console i get 500 error.
...

> Extra Info "attaching a screen shot would be very helpful"
<a href='https://postimg.cc/hzd9sLv6' target='_blank'><img src='https://i.postimg.cc/hzd9sLv6/Screenshot-2019-02-20-at-11-56-40-AM.png' border='0' alt='Screenshot-2019-02-20-at-11-56-40-AM'/></a>
...

> Do You Know A Solution For this Issue ?
Looking for the solution. Please Help.
...

**Comment by ctf0** [comment]
can u check the console for more info instead of just posting it here as it is :).

**Comment by masumonline** [comment]
I did. what i find the it cannot read the folder content.
here is the screen shot.

<a href='https://postimg.cc/v4ghGKFF' target='_blank'><img src='https://i.postimg.cc/6pzmfsM3/Screenshot-2019-02-20-at-3-47-03-PM.png' border='0' alt='Screenshot-2019-02-20-at-3-47-03-PM'/></a>

**Comment by ctf0** [comment]
thats a server error, so check ur network tab for the exact problem, plz check google or stack over flow for how to debug ur app
