### ISSUE TITLE
Support laravel 5.8

### ISSUE THREAD

**Issue by dinhchuong7913** [ctf0/Laravel-Media-Manager#80]
Hi
I have a error when install on laravel 5.8 
The requested package laravel/framework (locked at v5.7.27, required as 5.8.*) is satisfiable by laravel/framework[v5.7.27] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Conclusion: don't install ctf0/media-manager v3.3.1
    - Conclusion: don't install ctf0/media-manager v3.3.0
Please help me install

**Comment by ctf0** [comment]
actually i've updated the package and published the [release](https://github.com/ctf0/Laravel-Media-Manager/releases) but not sure why packagist didnt pick it up.

**Comment by dinhchuong7913** [comment]
I saw but still can not

**Comment by ctf0** [comment]
i will recheck the sync issue between packagist and the repo once i get home

**Comment by dinhchuong7913** [comment]
> i will recheck the sync issue between packagist and the repo once i get home

thank so much

**Comment by ctf0** [comment]
issue fixed, plz recheck
