### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by yezawhein** [ctf0/Laravel-Media-Manager#81]
![screenshot from 2019-03-08 12-18-46](https://user-images.githubusercontent.com/36364416/54010547-952dfa00-419d-11e9-8667-6226c29911be.jpeg)

**Comment by ctf0** [comment]
the issue have a template, plz use it
also try to search b4 opening new tickets, https://github.com/ctf0/Laravel-Media-Manager/issues/35#issuecomment-369896778
