### ISSUE TITLE
Can't install with laravel 5.8.3

### ISSUE THREAD

**Issue by tuandev-nv** [ctf0/Laravel-Media-Manager#82]
First, thank you because your nice package.
Second, please update composer.json to can install with laravel 5.8.2
Thank you so muck :)

> What version of Laravel are you using? (nothing lower than v5.4).
Laravel 5.8.3
> is it an issue related to installation or usage ?
Yes
> what is the error you are getting ?
`  Problem 1
    - Conclusion: don't install ctf0/media-manager v3.3
.2
    - Conclusion: don't install ctf0/media-manager v3.3
.1
    - Installation request for maennchen/zipstream-php
(locked at v0.5.2) -> satisfiable by maennchen/zipstrea
m-php[v0.5.2].
    - Conclusion: remove laravel/framework v5.8.3
    - Installation request for ctf0/media-manager ^3.3
-> satisfiable by ctf0/media-manager[v3.3.0, v3.3.1, v3
.3.2].
    - Conclusion: don't install laravel/framework v5.8.
3
`
> Do You Know A Solution For this Issue ?
I think composer.json required:
`"illuminate/support": "~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0",`

**Comment by ctf0** [comment]
the ticket have a template, plz use it.

**Comment by tuandev-nv** [comment]
> the ticket have a template, plz use it.

I updated my issue, thanks :)

**Comment by ctf0** [comment]
i believe ur problem is with `maennchen/zipstream-php` because u r using an old/diff version

**Comment by tuandev-nv** [comment]
> i believe ur problem is with `maennchen/zipstream-php` because u r using an old/diff version

Ahh, you are right, thanks !
