### ISSUE TITLE
AWS S3 Integration

### ISSUE THREAD

**Issue by g0shed** [ctf0/Laravel-Media-Manager#83]
> What version of Laravel are you using? (nothing lower than v5.4).

5.7

> is it an issue related to installation or usage ?

usage/installation

My question is simple, does it work with S3, and if so, how can I make the media manager read/write directly onto S3 or how can i configure it to use S3...

Thanks

**Comment by ctf0** [comment]
yes it does, and to upload directly its on [my list](https://github.com/ctf0/Laravel-Media-Manager/issues/11) but you can read more from https://dyrynda.com.au/blog/uploading-files-to-amazon-s3-from-the-browser-part-one
