### ISSUE TITLE
Unable to use with spatie/laravel-medialibrary (PHP-Zipstream version conflict)

### ISSUE THREAD

**Issue by nquillet** [ctf0/Laravel-Media-Manager#85]
Hello,

I want to use this awesome package alongside spatie/laravel-medialibrary

> What version of Laravel are you using? (nothing lower than v5.4).

Laravel Version 5.7.28

> is it an issue related to installation or usage ?

Issue related to the installation of the package

> what is the error you are getting ?

Conflict with spatie/laravel-medialibrary (7.6.0 and lower) https://github.com/spatie/laravel-medialibrary

> ctf0/media-manager v3.3.0 requires maennchen/zipstream-php ~1.0 -> satisfiable by maennchen/zipstream-php[v1.0.0-alpha.1, v1.0.0-alpha.2].

Spatie package requires zipstream ~0.4 and conflict with ctf0 package composer.json which requires ~1.0 (**For now Alpha releases..**)

> Do You Know A Solution For this Issue ?

Downgrade zipstream to last stable version -> 0.5.2

The issue is also known by spatie : https://github.com/spatie/laravel-medialibrary/issues/1000

Thanks

**Comment by ctf0** [comment]
i cant remember what exactly was the reason i decided to use the alpha version but i remember it had more pros than cons.

so sadly i cant downgrade the package dep version to play well with spatie :(

**Comment by nquillet** [comment]
Ok thanks for your quick answer ;)
