### ISSUE TITLE
Support for cloud drivers (Cloudinary)

### ISSUE THREAD

**Issue by BechirAhmed** [ctf0/Laravel-Media-Manager#86]
> What version of Laravel are you using? (nothing lower than v5.4).

v5.7

> is it an issue related to installation or usage ?

Usage

> what is the error you are getting ?

This driver does not support retrieving URLs.

> Extra Info "attaching a screen shot would be very helpful"

![Screenshot (60)](https://user-images.githubusercontent.com/18298101/55564480-8167ac00-56e7-11e9-98ca-b1d78f43d821.png)

I've installed some package to help use other driver with Laravel like [https://github.com/danhunsaker/laravel-flysystem-others](https://github.com/danhunsaker/laravel-flysystem-others) & [https://github.com/enl/flysystem-cloudinary](https://github.com/enl/flysystem-cloudinary), but whenever i change the default storage_disk from public the error is returned.

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
i think this is more related to the driver it self that it should support retrieving the url of the files,

still atm the package doesnt use laravel `Storage::url()` instead we get the path and resolve the url, so the driver should at least return the file path 
https://github.com/ctf0/Laravel-Media-Manager/blob/c96e6401f069e5a1a4c23b6503e7d797196701dc/src/Controllers/Modules/Utils.php#L60-L71

**Comment by BechirAhmed** [comment]
Okay thanks for clairing that
