### ISSUE TITLE
oh no something went wrong

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [ctf0/Laravel-Media-Manager#87]
> What version of Laravel are you using? (nothing lower than v5.4).

laravel 5.7

> is it an issue related to installation or usage ?

usage on deplyment

> what is the error you are getting ?

oh no something went wrong

> Extra Info "attaching a screen shot would be very helpful"

![Screenshot (148)](https://user-images.githubusercontent.com/44982504/56080160-ab6d4c80-5e12-11e9-957b-271b9a712182.png)
![Screenshot (149)](https://user-images.githubusercontent.com/44982504/56080161-ac05e300-5e12-11e9-917b-411b039a55e3.png)
![Screenshot (150)](https://user-images.githubusercontent.com/44982504/56080162-ac05e300-5e12-11e9-9aab-afcffc71f5f4.png)

> Do You Know A Solution For this Issue ?

not at this time

**Comment by adibenc** [comment]
https://stackoverflow.com/questions/38949781/pdo-exception-driver-not-found-in-laravel-for-sqlite

This is happened because i didn't have php-sqlite package. After installing & restart the apache & the app, it works on my project.

**Comment by ctf0** [comment]
@darvishiyan-mahdi sadly i cant really tell what actually have went wrong as the error code 500 is too generic, maybe try what @0x4164 have mentioned and re-check if u r still getting the same error

**Comment by chithien175** [comment]
under config/database.php add a new connection

'connection' => [
         'mediamanager' => [
            'driver'   => 'mysql', // or whatever you want
            'database' => env('DB_DATABASE'),
        ],
]

I added and succeeded

**Comment by chithien175** [comment]
fix file MediaController.php line 59 to:
$this->db = app('db')->connection('mysql')->table('locked');
or file database.php to:
'mediamanager' => 'mysql'

**Comment by ctf0** [comment]
@chithien175 https://github.com/ctf0/Laravel-Media-Manager/wiki/Lock-Files-&-Folder
