### ISSUE TITLE
Add a new logo

### ISSUE THREAD

**Issue by pedzed** [ctf0/Laravel-Media-Manager#88]
I saw issue #11 in which a logo is mentioned. I was thinking about something like this:

![laravel-file-manager](https://user-images.githubusercontent.com/8146593/56172616-93e8bc00-5fea-11e9-9d12-c902c4e0e932.png)

(I quickly did this in GIMP. If it is good, I might make a vector image and share an SVG version as well.)

**Comment by ctf0** [comment]
many many thanx for ur work, i was honestly thinking of doing something more artistic but i havent found the time for it yet
