### ISSUE TITLE
Add Dutch language

### ISSUE THREAD

**Issue by pedzed** [ctf0/Laravel-Media-Manager#89]
If people are interested, I might translate [`lang/en`](https://github.com/ctf0/Laravel-Media-Manager/tree/master/src/resources/lang/en) to `lang/nl` (Dutch).

**Comment by ctf0** [comment]
yes plz

**Comment by pedzed** [comment]
I'm sorry, but after looking better at the project, I find that it is below my quality standards. But I still wanted to contribute a little, so I added #92.
