### ISSUE TITLE
Can't Find Dependency "media.scss"

### ISSUE THREAD

**Issue by mckayze** [ctf0/Laravel-Media-Manager#9]
Error: /resources/assets/vendor/MediaManager/sass/undefined/media.scss,

I run: npm run dev, after installing everything but it gets to 95% and i get this error.

Not sure what details you need exactly but let me know and ill post them here.

**Comment by ctf0** [comment]
this is a serious fucken issue in the new L5.5

https://github.com/JeffreyWay/laravel-mix/issues/1155

**Comment by ctf0** [comment]
https://github.com/ctf0/Laravel-Media-Manager/commit/e17ad8cefe3f51d53535dd955829c5c782fcb615#diff-04c6e90faac2675aa89e2176d2eec7d8R168
