### ISSUE TITLE
Add NPM package

### ISSUE THREAD

**Issue by pedzed** [ctf0/Laravel-Media-Manager#91]
Rather than having to install all the NPM dependencies listed in the README, it would be better to only have one dependency: this package.

My suggestion is to add a `package.json` file with all the dependencies and registering it as an NPM package.

**Comment by ctf0** [comment]
i actually wish if there was a way i could add a `package.json` to the package and some how register it to the project/root `package.json` but i havent found the time to dig deeper yet
