### ISSUE TITLE
why close my question

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [ctf0/Laravel-Media-Manager#93]
my problem is with ajax request not style
> What version of Laravel are you using? (nothing lower than v5.4).

...

> is it an issue related to installation or usage ?

...

> what is the error you are getting ?

...

> Extra Info "attaching a screen shot would be very helpful"

...

> Do You Know A Solution For this Issue ?

...

**Comment by ctf0** [comment]
u dont need to reopen a new ticket just to ask `why close my question` , also i closed it because u didnt respond which was 5 days ago, anyway try to add more info in [the original ticket](https://github.com/ctf0/Laravel-Media-Manager/issues/87) so i or anyone else can help u
