### ISSUE TITLE
Show images selected for slider module

### ISSUE THREAD

**Issue by jasperf** [ctf0/Laravel-Media-Manager#95]
> What version of Laravel are you using? (nothing lower than v5.4).

We use Laravel 5.6

> is it an issue related to installation or usage ?

It is related to usage

> what is the error you are getting ?

Once we have selected multiple images using control select we can use these in a slider. We can then later on however not go back and see which ones were chosen. So how would we manage this?

> Do You Know A Solution For this Issue ?

Either we could somehow highlight currently applied or inserted images or show in a gallery tab which ones are being used.

**Comment by ctf0** [comment]
there is a btn in the filter bar area "next to the search bar to the top right" that can filter selected files

**Comment by jasperf** [comment]
Will look that up @ctf0 . Thanks for telling me.
