### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by xoxoj** [ctf0/Laravel-Media-Manager#96]
> What version of Laravel are you using? (nothing lower than v5.4).

5.8

> is it an issue related to installation or usage ?

yes

> what is the error you are getting ?

[Vue warn]: Failed to mount component: template or render function not defined.  found in  ---> <UsageIntroBtn>        <MediaManager> at resources/assets/vendor/MediaManager/js/components/manager.vue

> Extra Info "attaching a screen shot would be very helpful"

> Do You Know A Solution For this Issue ?

![1558077826552](https://user-images.githubusercontent.com/1118723/57910402-cd496b80-78b7-11e9-9001-9c97aec2c197.jpg)

**Comment by ctf0** [comment]
plz check the latest release, it should fix it

**Comment by xoxoj** [comment]
yes, i saw you change the code..

**Comment by xoxoj** [comment]
do you know? In fact, I have a nickname called the BUG hand. :D:D

**Comment by xoxoj** [comment]
I have also found at least 3 other bugs.

**Comment by ctf0** [comment]
> do you know? In fact, I have a nickname called the BUG hand. :D:D

lol

> I have also found at least 3 other bugs.

np, keep em coming
