### ISSUE TITLE
BUG:Uncaught (in promise) TypeError: path.replace is not a function

### ISSUE THREAD

**Issue by xoxoj** [ctf0/Laravel-Media-Manager#97]
> What version of Laravel are you using? (nothing lower than v5.4).

5.8

> is it an issue related to installation or usage ?

YES

> what is the error you are getting ?

`Uncaught (in promise) TypeError: path.replace is not a function`

> Extra Info "attaching a screen shot would be very helpful"

![1558081548365](https://user-images.githubusercontent.com/1118723/57914038-78f6b980-78c0-11e9-9e9c-96497950fd01.jpg)

> Do You Know A Solution For this Issue ?

Maybe

**Comment by xoxoj** [comment]
When the browser address is like this:

Http://media.test/media?path=sdf

Then refresh the browser, this BUG will appear

**Comment by ctf0** [comment]
https://github.com/ctf0/Laravel-Media-Manager/issues/94

**Comment by ctf0** [comment]
@xoxoj i cant repro, plz try to play with 

https://github.com/ctf0/Laravel-Media-Manager/blob/4b42464b14f0ee91bbb4e7b3fd12ef383a4d5337/src/resources/assets/js/modules/url.js#L13

and reply back with ur findings
