### ISSUE TITLE
BUG:  Editor

### ISSUE THREAD

**Issue by xoxoj** [ctf0/Laravel-Media-Manager#98]
> What version of Laravel are you using? (nothing lower than v5.4).

5.8

> is it an issue related to installation or usage ?

YES

> what is the error you are getting ?

Unable to display full information

> Extra Info "attaching a screen shot would be very helpful"

![1558081789521](https://user-images.githubusercontent.com/1118723/57914488-4f8a5d80-78c1-11e9-8cc0-f7a8a69c334b.jpg)

> Do You Know A Solution For this Issue ?

For example, I want to edit this photo and I can't display the full function button.

**Comment by ctf0** [comment]
plz check the console and reply back with the error

**Comment by xoxoj** [comment]
`[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Filters>
       <ImageEditor> at resources/assets/vendor/MediaManager/js/components/imageEditor/main.vue
         <MediaManager> at resources/assets/vendor/MediaManager/js/components/manager.vue
           <Root>`

**Comment by xoxoj** [comment]
I am using the version you just updated.

**Comment by xoxoj** [comment]
maybe here

`components: {
        filters: require('./filters/index.vue'),
        presets: require('./filters/presets.vue'),
        controls: require('./controls.vue'),
        // glitch: require('./glitch/index.vue'),
        imageCompare: require('vue-image-compare2')
    },`

change to 

`components: {
        filters: require('./filters/index.vue').default,
        presets: require('./filters/presets.vue').default,
        controls: require('./controls.vue').default,
        // glitch: require('./glitch/index.vue').default,
        imageCompare: require('vue-image-compare2').default
    },`

**Comment by ctf0** [comment]
okay i know where the error is, i'll republish the latest release again

**Comment by xoxoj** [comment]
wait...

**Comment by ctf0** [comment]
plz re-install with `dev-master`

**Comment by xoxoj** [comment]
1 second. Don't rush to release, there are more bugs, I will come up

**Comment by xoxoj** [comment]
![9999](https://user-images.githubusercontent.com/1118723/57915301-0d621b80-78c3-11e9-9030-f3616892ef03.jpg)

look here

**Comment by ctf0** [comment]
check console, this is probably related to css

**Comment by xoxoj** [comment]
useless, the console is clean

**Comment by ctf0** [comment]
am sure this is an issue with styling, try to check the width of the trimmed out area

**Comment by xoxoj** [comment]
Oh,  come on. body

How to modify it? Every time I go to modify it manually? Have you thought about it, if you have different sizes of pictures, how do you judge?

**Comment by ctf0** [comment]
okay then, i will check it later today

**Comment by xoxoj** [comment]
![999](https://user-images.githubusercontent.com/1118723/57916320-2ff53400-78c5-11e9-8c5d-8cab5cde2af2.jpg)
So every time I go to manual adjustment? Moreover, I modified this way, did not see the confirmation button

**Comment by ctf0** [comment]
> Moreover, I modified this way, did not see the confirmation button

am not sure i follow, but it will be fixed today

**Comment by xoxoj** [comment]
@ctf0 This project, I think it is very good, with a beautiful UI, good interaction design, rich features, is not just a project, but a very good product, I personally like it, very optimistic about it . And you are no longer a simple coder, with a very good view of the product, come on! !

**Comment by lucasmazevedo** [comment]
I have the same problem. Any solution ?? 
Great project .. Congratulations!

**Comment by ctf0** [comment]
its was related to a css style leak, will be fixed in next release
