### ISSUE TITLE
BUG:  cant click "Home" link.

### ISSUE THREAD

**Issue by xoxoj** [ctf0/Laravel-Media-Manager#99]
> What version of Laravel are you using? (nothing lower than v5.4).

5.8

> is it an issue related to installation or usage ?

YES

> what is the error you are getting ?

When I want to try to click the "Home" button, there is no effect, the "Close" button in the lower right corner is the same. No effect. (full browser size)

However, when I switch the browser to mobile browsing, I can click.

> Extra Info "attaching a screen shot would be very helpful"

![999](https://user-images.githubusercontent.com/1118723/57916699-fc66d980-78c5-11e9-814b-8d0f0ce21a64.jpg)

> Do You Know A Solution For this Issue ?

...

**Comment by onipp** [comment]
the bug can be fixed by adding "position: relative" style to li elements of breadcrumbs in desktop version

![](http://joxi.ru/1A5XY60cDJMzY2.jpg)

**Comment by ctf0** [comment]
@onipp can u make a PR with the fix ?

**Comment by onipp** [comment]
done

**Comment by ctf0** [comment]
@xoxoj @dee22 plz apply the fix to ur setup and reply back if it didnt work
